import React, { useState, useEffect } from "react";
import { BsFilterRight } from "react-icons/bs";

const MenuRightSide = ({ basketItems, setBasketItems }) => {
  // mimic db fetch - temporary
  let dbmenuitems = [
    {
      category: "Food",
      img: "./assets/breakfast.jpg",
      items: [
        {
          name: "Grilled Hake with Lemon Butter Sauce",
          tag: ["gluten-free"],
          subcategory: "special",
          subcategory_course: "2",
          stock: 5,
          price: 15,
          allergens: ["fish"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: true,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 350,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Hake fillet", "Lemon", "Butter", "Salt", "Pepper"],
        },
        {
          name: "Kids Mozzarella Sticks",
          tag: ["vegetarian"],
          subcategory: "kids",
          subcategory_course: "1",
          stock: 10,
          price: 2,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
        },
        {
          name: "Kids Garlic Bread",
          subcategory: "kids",
          subcategory_course: "1",
          tag: ["vegetarian"],
          stock: 10,
          price: 2,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
        },
        {
          name: "Kids Onion Rings",
          subcategory: "kids",
          subcategory_course: "1",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 2,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
        },
        {
          name: "Kids Chicken Nuggets",
          subcategory: "kids",
          subcategory_course: "2",
          cal: 250,
          tag: [],
          stock: 10,
          ingredients: ["chicken breast", "breadcrumbs", "spices"],
          price: 5,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Cheese Pizza",
          subcategory: "kids",
          subcategory_course: "2",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pizza dough", "tomato sauce", "mozzarella cheese"],
          price: 7,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Grilled Cheese Sandwich",
          subcategory: "kids",
          subcategory_course: "2",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["cheddar", "cheese", "bread", "butter"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 4,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Peanut Butter and Jelly Sandwich",
          subcategory: "kids",
          subcategory_course: "2",
          cal: 280,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["peanut butter", "jelly", "bread"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 3,
          allergens: [],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Macaroni and Cheese",
          subcategory: "kids",
          subcategory_course: "2",
          cal: 450,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["macaroni pasta", "cheddar cheese", "milk"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 7,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Mini Pancakes",
          subcategory: "kids",
          subcategory_course: "2",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pancake batter", "maple syrup", "fruits"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 6,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },

        {
          name: "Chocolate Brownie",
          subcategory: "desert",
          subcategory_course: "3",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["chocolate", "butter", "sugar", "eggs", "flour", "vanilla extract", "walnuts"],
          price: 8,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Cheesecake",
          subcategory: "desert",
          subcategory_course: "3",
          cal: 450,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["graham cracker crumbs", "butter", "cream cheese", "sugar", "sour cream", "vanilla extract", "eggs", "strawberry topping"],
          price: 8,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vanilla Ice Cream",
          subcategory: "desert",
          subcategory_course: "3",
          cal: 200,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["cream", "sugar", "vanilla extract"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Fruit Tart",
          subcategory: "desert",
          subcategory_course: "3",
          cal: 250,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pastry dough", "pastry cream", "strawberries", "kiwi", "blueberries", "apricot glaze"],
          price: 10,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Tiramisu",
          subcategory: "desert",
          subcategory_course: "3",
          cal: 320,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["ladyfingers", "espresso", "mascarpone cheese", "sugar", "cocoa powder", "rum or coffee liqueur"],
          price: 9,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Strawberry Shortcake",
          subcategory: "desert",
          subcategory_course: "3",
          cal: 280,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["shortcakes", "strawberries", "whipped cream", "sugar", "vanilla extract"],
          price: 6,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },

        // (((((((((((((((((((((((())))))))))))))))))))))))
        {
          name: "Grilled Salmon",
          subcategory: "main",
          subcategory_course: "2",
          cal: 400,
          tag: [],
          stock: 10,
          ingredients: ["salmon fillet", "lemon", "dill", "olive oil", "salt", "pepper"],
          price: 15,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Mixed Grill",
          subcategory: "main",
          subcategory_course: "2",
          cal: 2100,
          tag: [],
          stock: 10,
          ingredients: ["pork", "lamb", "beef", "sausage", "egg", "black pudding", "chips", "salad", "tomato", "mushroom", "gammon"],
          price: 20,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Beef Burger",
          subcategory: "main",
          subcategory_course: "2",
          cal: 500,
          tag: [],
          stock: 10,
          ingredients: ["beef patty", "brioche bun", "lettuce", "tomato", "onion", "cheese", "pickles"],
          price: 12,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vegetable Stir-Fry",
          subcategory: "main",
          subcategory_course: "2",
          cal: 300,
          tag: ["vegetarian", "vegan"],
          stock: 10,
          ingredients: ["mixed vegetables", "tofu", "soy sauce", "ginger", "garlic", "sesame oil"],
          price: 10,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Chicken Parmesan",
          subcategory: "main",
          subcategory_course: "2",
          cal: 450,
          tag: [],
          stock: 10,
          ingredients: ["chicken breast", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
          price: 14,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Pesto Pasta",
          subcategory: "main",
          subcategory_course: "2",
          cal: 380,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["penne pasta", "basil pesto", "cherry tomatoes", "pine nuts", "Parmesan cheese"],
          price: 11,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Shrimp Scampi",
          subcategory: "main",
          subcategory_course: "2",
          cal: 320,
          tag: [],
          stock: 10,
          ingredients: ["shrimp", "breadcrumbs", "lemon", "tartare", "chips", "salad", "parsley"],
          price: 16,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Mushroom Risotto",
          subcategory: "main",
          subcategory_course: "2",
          cal: 380,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["arborio rice", "mushrooms", "onion", "garlic", "vegetable broth", "Parmesan cheese"],
          price: 13,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Grilled Chicken Caesar Salad",
          subcategory: "main",
          subcategory_course: "2",
          cal: 320,
          tag: [],
          stock: 10,
          ingredients: ["grilled chicken breast", "romaine lettuce", "croutons", "Parmesan cheese", "Caesar dressing"],
          price: 9,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Beef Stroganoff",
          subcategory: "main",
          subcategory_course: "2",
          cal: 480,
          tag: [],
          stock: 10,
          ingredients: ["beef sirloin", "mushrooms", "onion", "garlic", "sour cream", "beef broth", "egg noodles"],
          price: 15,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Fish and Chips",
          subcategory: "main",
          subcategory_course: "2",
          cal: 550,
          tag: [],
          stock: 10,
          ingredients: ["white fish fillets", "flour", "beer", "potatoes", "tartar sauce", "lemon wedges"],
          price: 13,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Eggplant Parmesan",
          subcategory: "main",
          subcategory_course: "2",
          cal: 420,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggplant", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
          price: 12,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Lemon Herb Roasted Chicken",
          subcategory: "main",
          subcategory_course: "2",
          cal: 400,
          tag: [],
          stock: 10,
          ingredients: ["chicken", "lemon", "rosemary", "thyme", "garlic", "butter", "potatoes", "carrots"],
          price: 16,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vegetable Lasagna",
          subcategory: "main",
          subcategory_course: "2",
          cal: 360,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["lasagna noodles", "spinach", "mushrooms", "zucchini", "ricotta cheese", "marinara sauce", "mozzarella cheese"],
          price: 14,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },

        // ((((((((((((((((((((((((((((((()))))))))))))))))))))))))))))))
        {
          name: "Chicken Wings",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["chicken", "spicy"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 400,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Chicken wings", "Hot sauce", "Salt", "Pepper"],
        },
        {
          name: "Mozzarella Sticks",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["vegetarian"],
          stock: 10,
          price: 5,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
        },
        {
          name: "Garlic Bread",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["vegetarian"],
          stock: 10,
          price: 4,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
        },
        {
          name: "Onion Rings",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 4,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
        },
        {
          name: "Bruschetta",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 5,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Tomatoes", "Garlic", "Basil", "Olive oil"],
        },
        {
          name: "Shrimp Cocktail",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["shrimp", "seafood"],
          stock: 10,
          price: 7,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Shrimp", "Cocktail sauce", "Lemon", "Lettuce"],
        },
        {
          name: "Caprese Salad",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["vegetarian"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 200,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Tomatoes", "Mozzarella cheese", "Basil", "Balsamic glaze", "Salt"],
        },
        {
          name: "Spinach Artichoke Dip",
          subcategory: "starter",
          subcategory_course: "1",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Spinach", "Artichoke hearts", "Cream cheese", "Sour cream", "Parmesan cheese"],
        },
        {
          name: "Crispy Calamari",
          subcategory: "starter",
          subcategory_course: "1",
          cal: 300,
          tag: [],
          stock: 10,
          ingredients: ["calamari rings", "flour", "spices", "lemon wedges"],
          price: 10,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },

        // (((((((((((((((((((((((((((((((())))))))))))))))))))))))))))))))
        {
          name: "Full Breakfast",
          subcategory: "breakfast",
          subcategory_course: "2",
          cal: 350,
          tag: [],
          stock: 10,
          ingredients: ["free range eggs", "sausage", "bacon", "mushroom", "tomato", "baked beans", "toast", "butter"],
          price: 10,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Porridge",
          cal: 350,
          subcategory: "breakfast",
          subcategory_course: "2",
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["scottish oats", "milk", "honey", "wallnuts", "bannana"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: true,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: true,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Avocado on Toast",
          cal: 350,
          subcategory: "breakfast",
          subcategory_course: "2",
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["turmeric sourdough", "smashed avocado", "lemon", "cherry tomatoes", "feta cheese", "pomegranades", "watercress", "poached egg", "pine nuts"],
          price: 9,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Scrambled Eggs",
          cal: 300,
          subcategory: "breakfast",
          subcategory_course: "2",
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggs", "salt", "pepper", "butter"],
          price: 8,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "French Toast",
          cal: 400,
          subcategory: "breakfast",
          subcategory_course: "2",
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["bread", "eggs", "milk", "cinnamon", "sugar"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 7,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Yogurt Parfait",
          cal: 250,
          subcategory: "breakfast",
          subcategory_course: "2",
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["yogurt", "granola", "mixed berries", "honey"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Protein Pancakes",
          cal: 450,
          subcategory: "breakfast",
          subcategory_course: "2",
          tag: [],
          stock: 10,
          ingredients: ["oats", "protein powder", "banana", "eggs", "milk"],
          price: 10,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Veggie Omelette",
          cal: 300,
          subcategory: "breakfast",
          subcategory_course: "2",
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggs", "bell peppers", "onions", "spinach", "cheese"],
          price: 8,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },

    {
      category: "Beverages",
      img: "./assets/drinks.jpg",
      items: [
        {
          name: "Coca-Cola",
          tag: ["carbonated", "soft drink"],
          subcategory: "soft",
          stock: 10,
          price: 2,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "140",
          ingredients: ["Carbonated water", "High fructose corn syrup", "Caramel color", "Phosphoric acid", "Natural flavors", "Caffeine"],
        },
        {
          name: "Orange Juice",
          tag: ["fruit juice", "non-alcoholic"],
          subcategory: "soft",
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "110",
          ingredients: ["Orange juice"],
        },
        {
          name: "Apple Juice",
          tag: ["fruit juice", "non-alcoholic"],
          subcategory: "soft",
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "120",
          ingredients: ["Apple juice"],
        },
        {
          name: "Lemonade",
          tag: ["carbonated", "non-alcoholic"],
          subcategory: "soft",
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "100",
          ingredients: ["Lemon juice", "Water", "Sugar"],
        },
        {
          name: "Iced Tea",
          tag: ["beverage", "non-alcoholic"],
          subcategory: "coffee/tea",
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "60",
          ingredients: ["Black tea", "Water", "Sugar", "Lemon"],
        },
        {
          name: "Cucumber & Lime Water",
          tag: ["beverage", "non-alcoholic"],
          subcategory: "soft",
          stock: 10,
          price: 1,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "0",
          ingredients: ["Cucumber", "Lime", "Water"],
        },
        {
          name: "Mango Smoothie",
          tag: ["smoothie", "non-alcoholic"],
          subcategory: "mocktails",
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "220",
          ingredients: ["Mango", "Yogurt", "Milk", "Honey"],
        },
        {
          name: "Strawberry Banana Smoothie",
          tag: ["smoothie", "non-alcoholic"],
          subcategory: "mocktails",
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "180",
          ingredients: ["Strawberries", "Banana", "Yogurt", "Milk", "Honey"],
        },
        {
          name: "Chocolate Milkshake",
          tag: ["milkshake", "non-alcoholic"],
          subcategory: "mocktails",
          stock: 10,
          price: 5,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "420",
          ingredients: ["Chocolate ice cream", "Milk", "Whipped cream", "Chocolate syrup"],
        },
        {
          name: "Vanilla Milkshake",
          tag: ["milkshake", "non-alcoholic"],
          subcategory: "mocktails",
          stock: 10,
          price: 5,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "380",
          ingredients: ["Vanilla ice cream", "Milk", "Whipped cream", "Vanilla extract"],
        },
        {
          name: "Coffee",
          tag: ["hot beverage", "caffeinated"],
          subcategory: "coffee/tea",
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "5",
          ingredients: ["Coffee beans", "Water"],
        },
        {
          name: "Hot Chocolate",
          tag: ["hot beverage", "non-alcoholic"],
          subcategory: "coffee/tea",
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "150",
          ingredients: ["Cocoa powder", "Milk", "Sugar", "Whipped cream", "Chocolate shavings"],
        },
      ],
    },
    {
      category: "Bar Snacks",
      img: "./assets/drinks.jpg",
      items: [
        {
          name: "Roasted Mixed Nuts",
          tag: ["vegetarian", "vegan"],
          subcategory: "bar snacks",
          subcategory_course: "1",
          stock: 20,
          price: 3,
          allergens: ["nuts"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: true,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 150,
          img: "./assets/mixedNuts.jpg",
          ingredients: ["Cashews", "Almonds", "Peanuts", "Pistachios", "Salt"],
        },
      ],
    },
  ];
  const [searchValue, setSearchValue] = useState("");
  const handleInputChange = (event) => {
    setSearchValue(event.target.value);
  };

  useEffect(()=>{},[searchValue])


  const [menuType, setMenuType] = useState("Beverages");
  const [menuType2, setMenuType2] = useState("");
  const [menuType3, setMenuType3] = useState("");
  const [menuType4, setMenuType4] = useState("");

  // filter for beverages/food/barsnacks
  const changeMenuType = (e) => {
    setMenuType2("");
    setMenuType3("");
    setMenuType(e.target.innerText);
  };

  // filter for type of beverage
  const changeMenuType2 = (e) => {
    if (e.target.innerText === menuType2) {
      setMenuType2("");
      setMenuType3("");
    } else {
      setMenuType2(e.target.innerText);
    }
  };

  // filter for type of food
  const changeMenuType3 = (e) => {
    if (e.target.innerText === menuType3) {
      setMenuType3("");
    } else {
      setMenuType3(e.target.innerText);
    }
  };

  // filter for type of bar snack
  const changeMenuType4 = (e) => {
    if (e.target.innerText === menuType3) {
      setMenuType3("");
    } else {
      setMenuType3(e.target.innerText);
    }
  };

  const handleAddToMenu = (item) => {
    const id = crypto.randomUUID();
    const message = "";
    const existingItem = basketItems.find((menuItem) => menuItem.name === item.name);
    if (existingItem) {
      const updatedbasketItems = basketItems.map((menuItem) => {
        if (menuItem.name === item.name) {
          return {
            ...menuItem,
            qty: menuItem.qty + 1,
          };
        }
        return menuItem;
      });
      setBasketItems(updatedbasketItems);
    } else {
      setBasketItems([...basketItems, { ...item, id, message, qty: 1 }]);
    }
  };

  return (
    <>
      <div className="relative flex  mr-4 items-center max-[350px]:flex-wrap  max-[350px]:justify-center">
        <div className="relative grow mx-4">
          <input type="text" placeholder="Search..." className="w-[100%] mx-auto pl-10 pr-10 py-2 my-2 rounded" value={searchValue} onChange={handleInputChange} />
          <span className="absolute top-[28px] left-2 -translate-y-3">🔍</span>
          <button
            onClick={() => setSearchValue("")}
            className={`absolute top-[28px] right-5 -translate-y-3 ${searchValue ? "" : "hidden"}
									`}>
            ✖
          </button>
        </div>
        <button
          disabled={menuType2 === "" && menuType3 === "" && menuType4 === "" && searchValue === ""}
          onClick={() => {
            setSearchValue("");
            setMenuType2("");
            setMenuType3("");
            setMenuType4("");
          }}
          className={`p-2 ${menuType2 === "" && searchValue === "" && menuType3 === "" && menuType4 === "" ? "bg-[--c3]" : "bg-[--c1]"} rounded-xl shadow-xl border-b-2 border-b-black transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] active:shadow-[inset_0px_4px_2px_black]`}>
          Clear Filters
        </button>
      </div>

      <div className={`${searchValue !== "" ? "hidden":"grid"} grid-cols-3`}>
        <div onClick={changeMenuType} className={`${menuType === "Beverages" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 p-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
          Beverages
        </div>
        <div onClick={changeMenuType} className={`${menuType === "Food" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 p-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
          Food
        </div>
        <div onClick={changeMenuType} className={`${menuType === "Bar Snacks" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 p-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
          Bar Snacks
        </div>

        {menuType === "Beverages" && (
          <div className="Beverages transition grid grid-cols-7 col-span-3">
            <div onClick={changeMenuType2} className={`${menuType2 === "Coffee/Tea" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Coffee/Tea
            </div>
            <div onClick={changeMenuType2} className={`${menuType2 === "Soft" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Soft
            </div>
            <div onClick={changeMenuType2} className={`${menuType2 === "Lager" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Lager
            </div>
            <div onClick={changeMenuType2} className={`${menuType2 === "Cider" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Cider
            </div>
            <div onClick={changeMenuType2} className={`${menuType2 === "Spirits" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Spirits
            </div>
            <div onClick={changeMenuType2} className={`${menuType2 === "Cocktails" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Cocktails
            </div>
            <div onClick={changeMenuType2} className={`${menuType2 === "Mocktails" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Mocktails
            </div>
          </div>
        )}
        {menuType === "Food" && (
          <div className="other transition grid grid-cols-6 w-[100%] col-span-3">
            <div onClick={changeMenuType3} className={`${menuType3 === "Kids" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Kids
            </div>
            <div onClick={changeMenuType3} className={`${menuType3 === "Breakfast" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Breakfast
            </div>
            <div onClick={changeMenuType3} className={`${menuType3 === "Starter" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Starter
            </div>
            <div onClick={changeMenuType3} className={`${menuType3 === "Main" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Main
            </div>
            <div onClick={changeMenuType3} className={`${menuType3 === "Desert" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Desert
            </div>
            <div onClick={changeMenuType3} className={`${menuType3 === "Special" ? "shadow-[inset_0px_4px_2px_black] bg-[--c12]" : ""} border-b-2 border-b-black m-1 px-1 py-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1]`}>
              Special
            </div>
          </div>
        )}
        {menuType === "Bar Snacks" && <p className="text-center col-span-3">Range Bar Snacks</p>}
      </div>

      <div className="flex flex-wrap grow content-start overflow-y-scroll">
        {dbmenuitems
          .filter((category) => {
            if (searchValue !== "") {
              // Disregard other filters if searchValue is not empty
              return category.items.some((item) =>
                item.name.toLowerCase().includes(searchValue.toLowerCase())
              );
            } else {
              return (
                menuType === "" || category.category.toLowerCase() === menuType.toLowerCase()
              );
            }
          })
          .map((category, index) => {
            return (
              category.items
                // .filter((item) => menuType2 === "" || item.subcategory.toLowerCase() === menuType2.toLowerCase())
                .filter((item) => {
                  if (searchValue !== "") {
                    // Disregard other filters if searchValue is not empty
                    return item.name.toLowerCase().includes(searchValue.toLowerCase());
                  } else if (category.category === "Beverages") {
                    return menuType2 === "" || item.subcategory.toLowerCase() === menuType2.toLowerCase();
                  } else if (category.category === "Food") {
                    return menuType3 === "" || item.subcategory.toLowerCase() === menuType3.toLowerCase();
                  } else if (category.category === "Bar Snacks") {
                    return menuType4 === "" || item.subcategory.toLowerCase() === menuType4.toLowerCase();
                  }
                  return true; // No additional filter for other categories
                })
                .map((item, index2) => {
                  return (
                    <div key={category + index2} onClick={() => handleAddToMenu(item)} className="rounded h-[128px] w-[170px] flex flex-col shadow-xl m-1 p-1 transition duration-100 cursor-pointer hover:scale-[0.98] active:scale-[0.96] active:shadow-[inset_0px_2px_2px_black]">
                      <span className="text-end">{item.stock || 1}</span>
                      <span className="line-clamp-2 h-[48px] font-bold">{item.name}</span>
                      <span>£{item.price.toFixed(2)}</span>
                      <span className="h-[24px]">{item.allergens.join(", ")}</span>
                    </div>
                  );
                })
            );
          })}
      </div>

    </>
  );
};

export default MenuRightSide;
