import React, { useState, useEffect } from "react";
import { BrowserRouter, Routes, Route, Outlet, NavLink, useNavigate, useLocation } from "react-router-dom";
import "./Menu.css";
import { getUser, getVenue } from "../../utils/authUser";
import VenueNTable from "./VenueNTable";

import { AiFillCaretRight, AiOutlineLeft } from "react-icons/ai";
import { BsFilterRight } from "react-icons/bs";
import { CiGrid2H, CiGrid41 } from "react-icons/ci";

import MenuLeftSide from "./MenuLeftSide";
import MenuRightSide from "./MenuRightSide";

const Menu = ({ basketItems, setBasketItems, toggleGrid, setToggleGrid, toggleFilters, setToggleFilters, searchValue, setSearchValue, selectedKCal, setSelectedKCal, selectedDietary, setSelectedDietary, venues, venueNtable, setVenueNtable }) => {
  const dbmenuitems = [
    {
      name: "Breakfast",
      img: "./assets/breakfast.jpg",
      items: [
        {
          name: "Full Breakfast",
          cal: 350,
          tag: [],
          stock: 10,
          ingredients: ["free range eggs", "sausage", "bacon", "mushroom", "tomato", "baked beans", "toast", "butter"],
          price: 10,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Porridge",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["scottish oats", "milk", "honey", "wallnuts", "bannana"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: true,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: true,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Avocado on Toast",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["turmeric sourdough", "smashed avocado", "lemon", "cherry tomatoes", "feta cheese", "pomegranades", "watercress", "poached egg", "pine nuts"],
          price: 9,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Scrambled Eggs",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggs", "salt", "pepper", "butter"],
          price: 8,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "French Toast",
          cal: 400,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["bread", "eggs", "milk", "cinnamon", "sugar"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 7,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Yogurt Parfait",
          cal: 250,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["yogurt", "granola", "mixed berries", "honey"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Protein Pancakes",
          cal: 450,
          tag: [],
          stock: 10,
          ingredients: ["oats", "protein powder", "banana", "eggs", "milk"],
          price: 10,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Veggie Omelette",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggs", "bell peppers", "onions", "spinach", "cheese"],
          price: 8,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Kids Starters",
      img: "./assets/kids.jpg",
      items: [
        {
          name: "Kids Mozzarella Sticks",
          tag: ["vegetarian"],
          stock: 10,
          price: 2,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
        },
        {
          name: "Kids Garlic Bread",
          tag: ["vegetarian"],
          stock: 10,
          price: 2,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
        },
        {
          name: "Kids Onion Rings",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 2,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
        },
      ],
    },
    {
      name: "Kids Mains",
      img: "./assets/kids.jpg",
      items: [
        {
          name: "Kids Chicken Nuggets",
          cal: 250,
          tag: [],
          stock: 10,
          ingredients: ["chicken breast", "breadcrumbs", "spices"],
          price: 5,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Cheese Pizza",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pizza dough", "tomato sauce", "mozzarella cheese"],
          price: 7,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Grilled Cheese Sandwich",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["cheddar", "cheese", "bread", "butter"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 4,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Peanut Butter and Jelly Sandwich",
          cal: 280,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["peanut butter", "jelly", "bread"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 3,
          allergens: [],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Macaroni and Cheese",
          cal: 450,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["macaroni pasta", "cheddar cheese", "milk"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 7,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Mini Pancakes",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pancake batter", "maple syrup", "fruits"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 6,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Beverages",
      img: "./assets/drinks.jpg",
      items: [
        {
          name: "Coca-Cola",
          tag: ["carbonated", "soft drink"],
          stock: 10,
          price: 2,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "140",
          ingredients: ["Carbonated water", "High fructose corn syrup", "Caramel color", "Phosphoric acid", "Natural flavors", "Caffeine"],
        },
        {
          name: "Orange Juice",
          tag: ["fruit juice", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "110",
          ingredients: ["Orange juice"],
        },
        {
          name: "Apple Juice",
          tag: ["fruit juice", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "120",
          ingredients: ["Apple juice"],
        },
        {
          name: "Lemonade",
          tag: ["carbonated", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "100",
          ingredients: ["Lemon juice", "Water", "Sugar"],
        },
        {
          name: "Iced Tea",
          tag: ["beverage", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "60",
          ingredients: ["Black tea", "Water", "Sugar", "Lemon"],
        },
        {
          name: "Cucumber & Lime Water",
          tag: ["beverage", "non-alcoholic"],
          stock: 10,
          price: 1,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "0",
          ingredients: ["Cucumber", "Lime", "Water"],
        },
        {
          name: "Mango Smoothie",
          tag: ["smoothie", "non-alcoholic"],
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "220",
          ingredients: ["Mango", "Yogurt", "Milk", "Honey"],
        },
        {
          name: "Strawberry Banana Smoothie",
          tag: ["smoothie", "non-alcoholic"],
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "180",
          ingredients: ["Strawberries", "Banana", "Yogurt", "Milk", "Honey"],
        },
        {
          name: "Chocolate Milkshake",
          tag: ["milkshake", "non-alcoholic"],
          stock: 10,
          price: 5,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "420",
          ingredients: ["Chocolate ice cream", "Milk", "Whipped cream", "Chocolate syrup"],
        },
        {
          name: "Vanilla Milkshake",
          tag: ["milkshake", "non-alcoholic"],
          stock: 10,
          price: 5,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "380",
          ingredients: ["Vanilla ice cream", "Milk", "Whipped cream", "Vanilla extract"],
        },
        {
          name: "Coffee",
          tag: ["hot beverage", "caffeinated"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "5",
          ingredients: ["Coffee beans", "Water"],
        },
        {
          name: "Hot Chocolate",
          tag: ["hot beverage", "non-alcoholic"],
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "150",
          ingredients: ["Cocoa powder", "Milk", "Sugar", "Whipped cream", "Chocolate shavings"],
        },
      ],
    },
    {
      name: "Starters",
      img: "./assets/starters.jpg",
      items: [
        {
          name: "Chicken Wings",
          tag: ["chicken", "spicy"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 400,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Chicken wings", "Hot sauce", "Salt", "Pepper"],
        },
        {
          name: "Mozzarella Sticks",
          tag: ["vegetarian"],
          stock: 10,
          price: 5,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
        },
        {
          name: "Garlic Bread",
          tag: ["vegetarian"],
          stock: 10,
          price: 4,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
        },
        {
          name: "Onion Rings",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 4,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
        },
        {
          name: "Bruschetta",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 5,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Tomatoes", "Garlic", "Basil", "Olive oil"],
        },
        {
          name: "Shrimp Cocktail",
          tag: ["shrimp", "seafood"],
          stock: 10,
          price: 7,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Shrimp", "Cocktail sauce", "Lemon", "Lettuce"],
        },
        {
          name: "Caprese Salad",
          tag: ["vegetarian"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 200,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Tomatoes", "Mozzarella cheese", "Basil", "Balsamic glaze", "Salt"],
        },
        {
          name: "Spinach Artichoke Dip",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Spinach", "Artichoke hearts", "Cream cheese", "Sour cream", "Parmesan cheese"],
        },
        {
          name: "Crispy Calamari",
          cal: 300,
          tag: [],
          stock: 10,
          ingredients: ["calamari rings", "flour", "spices", "lemon wedges"],
          price: 10,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Mains",
      img: "./assets/mains.jpeg",
      items: [
        {
          name: "Grilled Salmon",
          cal: 400,
          tag: [],
          stock: 10,
          ingredients: ["salmon fillet", "lemon", "dill", "olive oil", "salt", "pepper"],
          price: 15,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Mixed Grill",
          cal: 2100,
          tag: [],
          stock: 10,
          ingredients: ["pork", "lamb", "beef", "sausage", "egg", "black pudding", "chips", "salad", "tomato", "mushroom", "gammon"],
          price: 20,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Beef Burger",
          cal: 500,
          tag: [],
          stock: 10,
          ingredients: ["beef patty", "brioche bun", "lettuce", "tomato", "onion", "cheese", "pickles"],
          price: 12,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vegetable Stir-Fry",
          cal: 300,
          tag: ["vegetarian", "vegan"],
          stock: 10,
          ingredients: ["mixed vegetables", "tofu", "soy sauce", "ginger", "garlic", "sesame oil"],
          price: 10,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Chicken Parmesan",
          cal: 450,
          tag: [],
          stock: 10,
          ingredients: ["chicken breast", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
          price: 14,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Pesto Pasta",
          cal: 380,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["penne pasta", "basil pesto", "cherry tomatoes", "pine nuts", "Parmesan cheese"],
          price: 11,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Shrimp Scampi",
          cal: 320,
          tag: [],
          stock: 10,
          ingredients: ["shrimp", "breadcrumbs", "lemon", "tartare", "chips", "salad", "parsley"],
          price: 16,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Mushroom Risotto",
          cal: 380,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["arborio rice", "mushrooms", "onion", "garlic", "vegetable broth", "Parmesan cheese"],
          price: 13,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Grilled Chicken Caesar Salad",
          cal: 320,
          tag: [],
          stock: 10,
          ingredients: ["grilled chicken breast", "romaine lettuce", "croutons", "Parmesan cheese", "Caesar dressing"],
          price: 9,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Beef Stroganoff",
          cal: 480,
          tag: [],
          stock: 10,
          ingredients: ["beef sirloin", "mushrooms", "onion", "garlic", "sour cream", "beef broth", "egg noodles"],
          price: 15,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Fish and Chips",
          cal: 550,
          tag: [],
          stock: 10,
          ingredients: ["white fish fillets", "flour", "beer", "potatoes", "tartar sauce", "lemon wedges"],
          price: 13,
          allergens: ["nut free", "dairy free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Eggplant Parmesan",
          cal: 420,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggplant", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
          price: 12,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Lemon Herb Roasted Chicken",
          cal: 400,
          tag: [],
          stock: 10,
          ingredients: ["chicken", "lemon", "rosemary", "thyme", "garlic", "butter", "potatoes", "carrots"],
          price: 16,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vegetable Lasagna",
          cal: 360,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["lasagna noodles", "spinach", "mushrooms", "zucchini", "ricotta cheese", "marinara sauce", "mozzarella cheese"],
          price: 14,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Desserts",
      img: "./assets/deserts.jpg",
      items: [
        {
          name: "Chocolate Brownie",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["chocolate", "butter", "sugar", "eggs", "flour", "vanilla extract", "walnuts"],
          price: 8,
          allergens: [],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Cheesecake",
          cal: 450,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["graham cracker crumbs", "butter", "cream cheese", "sugar", "sour cream", "vanilla extract", "eggs", "strawberry topping"],
          price: 8,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vanilla Ice Cream",
          cal: 200,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["cream", "sugar", "vanilla extract"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Fruit Tart",
          cal: 250,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pastry dough", "pastry cream", "strawberries", "kiwi", "blueberries", "apricot glaze"],
          price: 10,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Tiramisu",
          cal: 320,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["ladyfingers", "espresso", "mascarpone cheese", "sugar", "cocoa powder", "rum or coffee liqueur"],
          price: 9,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Strawberry Shortcake",
          cal: 280,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["shortcakes", "strawberries", "whipped cream", "sugar", "vanilla extract"],
          price: 6,
          allergens: ["nut free"],
          priceOffer: null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
  ];

  const nav = useNavigate();
  const [menuitems, setMenuitems] = useState(dbmenuitems);
  const [user, setUser] = useState(null);

  useEffect(() => {
    getUser(setUser);
    getVenue(setVenueNtable);
  }, []);

  const handleInputChange = (event) => {
    setSearchValue(event.target.value);
  };

  const [viewSearch, setViewSearch] = useState(false);

  const location = useLocation();
  const isBaseRoute = location.pathname === "/menu";

  const handleF1 = (event) => {
    setSelectedKCal(event.target.name);
  };
  const handleF2 = (event) => {
    setSelectedDietary(event.target.name);
  };

  const handleItemClick = (c, i) => {
    // Navigate to the item details route
    nav(`/${c}/${i}`);
  };

  const [basketTotal, setBasketTotal] = useState(0)
  const [totalProducts, setTotalProducts] = useState(0);
  useEffect(()=>{

    setBasketTotal(basketItems.reduce((total, item) => {
      return total + item.price * item.qty;
    }, 0).toFixed(2))

  
    setTotalProducts(basketItems.reduce((total, item) => {
      return total + item.qty;
    }, 0));


  },[basketItems])

  const handleDeleteAll = () => {
    setBasketItems([]);
  };

  if (!venueNtable.venue || !venueNtable.table) return <VenueNTable venues={venues} venueNtable={venueNtable} setVenueNtable={setVenueNtable} />;

  return (
    <>
      {!venueNtable.venue || (!venueNtable.table && <VenueNTable venues={venues} venueNtable={venueNtable} setVenueNtable={setVenueNtable} />)}

      <div className="grid grid-cols-[2fr_3fr] gap-1 rounded h-[100%] w-[100%]">
        <div className="h-[100%] w-[100%] rounded shadow-xl flex flex-col p-1 overflow-hidden">
          <div className="grid grid-cols-4 gap-2 h-[82px]">
            <button onClick={handleDeleteAll} className="text-sm bg-red-300 m-1 p-2 rounded-xl transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] flex flex-col justify-center items-center border-b-2 border-b-black ">
              <span>Delete ALL</span>
              <span>{totalProducts}</span>
            </button>
            <div className="tableNumber m-1 p-2 transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90] rounded-xl flex flex-col text-center text-sm justify-center font-semibold bg-[--c1] border-b-2 border-b-black ">
              <p>Table</p>
              <p className="text-3xl">{venueNtable.table}</p>
            </div>
            <button onClick={()=>{setVenueNtable((prevValues) => ({ ...prevValues, table: null })); console.log("dev**to check -> confirm merge if any items -> merge -> change table in db") }} className="text-sm bg-gray-300 m-1 p-2 rounded-xl transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90]  flex flex-col justify-center items-center border-b-2 border-b-black ">
              <span>Transfer</span>
              <span>Table</span>
            </button>
            <button onClick={()=>{setVenueNtable((prevValues) => ({ ...prevValues, table: null })); console.log("dev**to change table in db"); }} className="text-sm bg-gray-300 m-1 p-2 rounded-xl transition-all cursor-pointer hover:scale-[0.98] active:scale-[0.90]  flex flex-col justify-center items-center border-b-2 border-b-black ">
              <span>Open</span>
              <span>Table</span>
            </button>
          </div>

          <div className="MenuLeftSide flex flex-col overflow-hidden grow">
            <div className="MenuLeftSide flex flex-col overflow-y-scroll">
            <MenuLeftSide basketItems={basketItems} setBasketItems={setBasketItems} />
            </div>
            <div className="text-3xl text-end mt-auto flex justify-between">
              <div>
              <span>Items: </span><span className="font-bold">{totalProducts}</span></div>
              <div>
                <span>Total: </span><span className="font-bold">£{basketTotal}</span>
              </div>
            </div>
          </div>
        </div>

        <div className="MenuRightSide h-[100%] w-[100%] rounded shadow-xl p-1 flex flex-col overflow-hidden">
          <MenuRightSide basketItems={basketItems} setBasketItems={setBasketItems} />
        </div>
      </div>
    </>
  );
};

export default Menu;
