import React, { useState, useEffect } from "react";
import "./Menu.css";
import VenueNTable from "./VenueNTable";

import { AiFillCaretRight, AiOutlineLeft } from "react-icons/ai";
import { BsFilterRight } from "react-icons/bs";
import { CiGrid2H, CiGrid41 } from "react-icons/ci";
import MenuItem from "./MenuItem";
import { BrowserRouter, Routes, Route, Outlet, NavLink, useNavigate, useLocation } from "react-router-dom";

import {getUser, getVenue} from "../../utils/authUser"

const Menu = ({ toggleGrid, setToggleGrid, toggleFilters, setToggleFilters, searchValue, setSearchValue, selectedKCal, setSelectedKCal, selectedDietary, setSelectedDietary, venues, venueNtable, setVenueNtable }) => {
  const dbmenuitems = [
    {
      name: "Breakfast",
      img: "./assets/breakfast.jpg",
      items: [
        {
          name: "Full Breakfast",
          cal: 350,
          tag: [],
          stock: 10,
          ingredients: [
            "free range eggs",
            "sausage",
            "bacon",
            "mushroom",
            "tomato",
            "baked beans",
            "toast",
            "butter",
          ],
          price: 10,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Porridge",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["scottish oats", "milk", "honey", "wallnuts", "bannana"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: true,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: true,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Avocado on Toast",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "turmeric sourdough",
            "smashed avocado",
            "lemon",
            "cherry tomatoes",
            "feta cheese",
            "pomegranades",
            "watercress",
            "poached egg",
            "pine nuts",
          ],
          price: 9,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Scrambled Eggs",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggs", "salt", "pepper", "butter"],
          price: 8,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "French Toast",
          cal: 400,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["bread", "eggs", "milk", "cinnamon", "sugar"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 7,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Yogurt Parfait",
          cal: 250,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["yogurt", "granola", "mixed berries", "honey"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Protein Pancakes",
          cal: 450,
          tag: [],
          stock: 10,
          ingredients: ["oats", "protein powder", "banana", "eggs", "milk"],
          price: 10,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Veggie Omelette",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["eggs", "bell peppers", "onions", "spinach", "cheese"],
          price: 8,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Kids Starters",
      img: "./assets/kids.jpg",
      items: [
        {
          name: "Kids Mozzarella Sticks",
          tag: ["vegetarian"],
          stock: 10,
          price: 2,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: [
            "Mozzarella cheese sticks",
            "Breadcrumbs",
            "Eggs",
            "Flour",
            "Marinara sauce",
          ],
        },
        {
          name: "Kids Garlic Bread",
          tag: ["vegetarian"],
          stock: 10,
          price: 2,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
        },
        {
          name: "Kids Onion Rings",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 2,
          allergens: ["nut free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
        },
      ],
    },
    {
      name: "Kids Mains",
      img: "./assets/kids.jpg",
      items: [
        {
          name: "Kids Chicken Nuggets",
          cal: 250,
          tag: [],
          stock: 10,
          ingredients: ["chicken breast", "breadcrumbs", "spices"],
          price: 5,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Cheese Pizza",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pizza dough", "tomato sauce", "mozzarella cheese"],
          price: 7,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Grilled Cheese Sandwich",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["cheddar", "cheese", "bread", "butter"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 4,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Peanut Butter and Jelly Sandwich",
          cal: 280,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["peanut butter", "jelly", "bread"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 3,
          allergens: [],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Macaroni and Cheese",
          cal: 450,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["macaroni pasta", "cheddar cheese", "milk"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 7,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Kids Mini Pancakes",
          cal: 300,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["pancake batter", "maple syrup", "fruits"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          price: 6,
          allergens: ["nut free"],
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Beverages",
      img: "./assets/drinks.jpg",
      items: [
        {
          name: "Coca-Cola",
          tag: ["carbonated", "soft drink"],
          stock: 10,
          price: 2,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "140",
          ingredients: [
            "Carbonated water",
            "High fructose corn syrup",
            "Caramel color",
            "Phosphoric acid",
            "Natural flavors",
            "Caffeine",
          ],
        },
        {
          name: "Orange Juice",
          tag: ["fruit juice", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "110",
          ingredients: ["Orange juice"],
        },
        {
          name: "Apple Juice",
          tag: ["fruit juice", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "120",
          ingredients: ["Apple juice"],
        },
        {
          name: "Lemonade",
          tag: ["carbonated", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "100",
          ingredients: ["Lemon juice", "Water", "Sugar"],
        },
        {
          name: "Iced Tea",
          tag: ["beverage", "non-alcoholic"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "60",
          ingredients: ["Black tea", "Water", "Sugar", "Lemon"],
        },
        {
          name: "Cucumber & Lime Water",
          tag: ["beverage", "non-alcoholic"],
          stock: 10,
          price: 1,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "0",
          ingredients: ["Cucumber", "Lime", "Water"],
        },
        {
          name: "Mango Smoothie",
          tag: ["smoothie", "non-alcoholic"],
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "220",
          ingredients: ["Mango", "Yogurt", "Milk", "Honey"],
        },
        {
          name: "Strawberry Banana Smoothie",
          tag: ["smoothie", "non-alcoholic"],
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "180",
          ingredients: ["Strawberries", "Banana", "Yogurt", "Milk", "Honey"],
        },
        {
          name: "Chocolate Milkshake",
          tag: ["milkshake", "non-alcoholic"],
          stock: 10,
          price: 5,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "420",
          ingredients: [
            "Chocolate ice cream",
            "Milk",
            "Whipped cream",
            "Chocolate syrup",
          ],
        },
        {
          name: "Vanilla Milkshake",
          tag: ["milkshake", "non-alcoholic"],
          stock: 10,
          price: 5,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "380",
          ingredients: [
            "Vanilla ice cream",
            "Milk",
            "Whipped cream",
            "Vanilla extract",
          ],
        },
        {
          name: "Coffee",
          tag: ["hot beverage", "caffeinated"],
          stock: 10,
          price: 3,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "5",
          ingredients: ["Coffee beans", "Water"],
        },
        {
          name: "Hot Chocolate",
          tag: ["hot beverage", "non-alcoholic"],
          stock: 10,
          price: 4,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDrink.jpg",
          calories: "150",
          ingredients: [
            "Cocoa powder",
            "Milk",
            "Sugar",
            "Whipped cream",
            "Chocolate shavings",
          ],
        },
      ],
    },
    {
      name: "Starters",
      img: "./assets/starters.jpg",
      items: [
        {
          name: "Chicken Wings",
          tag: ["chicken", "spicy"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 400,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Chicken wings", "Hot sauce", "Salt", "Pepper"],
        },
        {
          name: "Mozzarella Sticks",
          tag: ["vegetarian"],
          stock: 10,
          price: 5,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: [
            "Mozzarella cheese sticks",
            "Breadcrumbs",
            "Eggs",
            "Flour",
            "Marinara sauce",
          ],
        },
        {
          name: "Garlic Bread",
          tag: ["vegetarian"],
          stock: 10,
          price: 4,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
        },
        {
          name: "Onion Rings",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 4,
          allergens: ["nut free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
        },
        {
          name: "Bruschetta",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 5,
          allergens: ["nut free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Baguette", "Tomatoes", "Garlic", "Basil", "Olive oil"],
        },
        {
          name: "Shrimp Cocktail",
          tag: ["shrimp", "seafood"],
          stock: 10,
          price: 7,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: ["Shrimp", "Cocktail sauce", "Lemon", "Lettuce"],
        },
        {
          name: "Caprese Salad",
          tag: ["vegetarian"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 200,
          img: "./assets/defaultDish.jpg",
          ingredients: [
            "Tomatoes",
            "Mozzarella cheese",
            "Basil",
            "Balsamic glaze",
            "Salt",
          ],
        },
        {
          name: "Spinach Artichoke Dip",
          tag: ["vegetarian", "vegan"],
          stock: 10,
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          cal: 300,
          img: "./assets/defaultDish.jpg",
          ingredients: [
            "Spinach",
            "Artichoke hearts",
            "Cream cheese",
            "Sour cream",
            "Parmesan cheese",
          ],
        },
        {
          name: "Crispy Calamari",
          cal: 300,
          tag: [],
          stock: 10,
          ingredients: ["calamari rings", "flour", "spices", "lemon wedges"],
          price: 10,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Mains",
      img: "./assets/mains.jpeg",
      items: [
        {
          name: "Grilled Salmon",
          cal: 400,
          tag: [],
          stock: 10,
          ingredients: [
            "salmon fillet",
            "lemon",
            "dill",
            "olive oil",
            "salt",
            "pepper",
          ],
          price: 15,
          allergens: ["nut free", "gluten free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Mixed Grill",
          cal: 2100,
          tag: [],
          stock: 10,
          ingredients: [
            "pork",
            "lamb",
            "beef",
            "sausage",
            "egg",
            "black pudding",
            "chips",
            "salad",
            "tomato",
            "mushroom",
            "gammon",
          ],
          price: 20,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Beef Burger",
          cal: 500,
          tag: [],
          stock: 10,
          ingredients: [
            "beef patty",
            "brioche bun",
            "lettuce",
            "tomato",
            "onion",
            "cheese",
            "pickles",
          ],
          price: 12,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vegetable Stir-Fry",
          cal: 300,
          tag: ["vegetarian", "vegan"],
          stock: 10,
          ingredients: [
            "mixed vegetables",
            "tofu",
            "soy sauce",
            "ginger",
            "garlic",
            "sesame oil",
          ],
          price: 10,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Chicken Parmesan",
          cal: 450,
          tag: [],
          stock: 10,
          ingredients: [
            "chicken breast",
            "bread crumbs",
            "Parmesan cheese",
            "marinara sauce",
            "mozzarella cheese",
            "spaghetti",
          ],
          price: 14,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Pesto Pasta",
          cal: 380,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "penne pasta",
            "basil pesto",
            "cherry tomatoes",
            "pine nuts",
            "Parmesan cheese",
          ],
          price: 11,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Shrimp Scampi",
          cal: 320,
          tag: [],
          stock: 10,
          ingredients: [
            "shrimp",
            "breadcrumbs",
            "lemon",
            "tartare",
            "chips",
            "salad",
            "parsley",
          ],
          price: 16,
          allergens: ["nut free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Mushroom Risotto",
          cal: 380,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "arborio rice",
            "mushrooms",
            "onion",
            "garlic",
            "vegetable broth",
            "Parmesan cheese",
          ],
          price: 13,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Grilled Chicken Caesar Salad",
          cal: 320,
          tag: [],
          stock: 10,
          ingredients: [
            "grilled chicken breast",
            "romaine lettuce",
            "croutons",
            "Parmesan cheese",
            "Caesar dressing",
          ],
          price: 9,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Beef Stroganoff",
          cal: 480,
          tag: [],
          stock: 10,
          ingredients: [
            "beef sirloin",
            "mushrooms",
            "onion",
            "garlic",
            "sour cream",
            "beef broth",
            "egg noodles",
          ],
          price: 15,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Fish and Chips",
          cal: 550,
          tag: [],
          stock: 10,
          ingredients: [
            "white fish fillets",
            "flour",
            "beer",
            "potatoes",
            "tartar sauce",
            "lemon wedges",
          ],
          price: 13,
          allergens: ["nut free", "dairy free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Eggplant Parmesan",
          cal: 420,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "eggplant",
            "bread crumbs",
            "Parmesan cheese",
            "marinara sauce",
            "mozzarella cheese",
            "spaghetti",
          ],
          price: 12,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Lemon Herb Roasted Chicken",
          cal: 400,
          tag: [],
          stock: 10,
          ingredients: [
            "chicken",
            "lemon",
            "rosemary",
            "thyme",
            "garlic",
            "butter",
            "potatoes",
            "carrots",
          ],
          price: 16,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vegetable Lasagna",
          cal: 360,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "lasagna noodles",
            "spinach",
            "mushrooms",
            "zucchini",
            "ricotta cheese",
            "marinara sauce",
            "mozzarella cheese",
          ],
          price: 14,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
    {
      name: "Desserts",
      img: "./assets/deserts.jpg",
      items: [
        {
          name: "Chocolate Brownie",
          cal: 350,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "chocolate",
            "butter",
            "sugar",
            "eggs",
            "flour",
            "vanilla extract",
            "walnuts",
          ],
          price: 8,
          allergens: [],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Cheesecake",
          cal: 450,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "graham cracker crumbs",
            "butter",
            "cream cheese",
            "sugar",
            "sour cream",
            "vanilla extract",
            "eggs",
            "strawberry topping",
          ],
          price: 8,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Vanilla Ice Cream",
          cal: 200,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: ["cream", "sugar", "vanilla extract"],
          price: 6,
          allergens: ["nut free", "gluten free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Fruit Tart",
          cal: 250,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "pastry dough",
            "pastry cream",
            "strawberries",
            "kiwi",
            "blueberries",
            "apricot glaze",
          ],
          price: 10,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Tiramisu",
          cal: 320,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "ladyfingers",
            "espresso",
            "mascarpone cheese",
            "sugar",
            "cocoa powder",
            "rum or coffee liqueur",
          ],
          price: 9,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
        {
          name: "Strawberry Shortcake",
          cal: 280,
          tag: ["vegetarian"],
          stock: 10,
          ingredients: [
            "shortcakes",
            "strawberries",
            "whipped cream",
            "sugar",
            "vanilla extract",
          ],
          price: 6,
          allergens: ["nut free"],
          priceOffer:null,
          allergensList: {
            Meat: false,
            Celery: false,
            Crustaceans: false,
            Fish: false,
            Milk: false,
            Mustard: false,
            Peanuts: false,
            Soybeans: false,
            Gluten: false,
            Egg: false,
            Lupin: false,
            Moluscs: false,
            Nuts: false,
            SesameSeeds: false,
            Sulphur: false,
          },
          img: "./assets/defaultDish.jpg",
        },
      ],
    },
  ];

  const nav = useNavigate();
  const [menuitems, setMenuitems] = useState(dbmenuitems);
  const [user,setUser] = useState(null)

  useEffect(() => {
    getUser(setUser)
    getVenue(setVenueNtable)
  }, []);

  const handleInputChange = (event) => {
    setSearchValue(event.target.value);
  };

  const [viewSearch, setViewSearch] = useState(false);

  const location = useLocation();
  const isBaseRoute = location.pathname === "/menu";

  const handleF1 = (event) => {
    setSelectedKCal(event.target.name);
  };
  const handleF2 = (event) => {
    setSelectedDietary(event.target.name);
  };

  const handleItemClick = (c, i) => {
    // Navigate to the item details route
    nav(`/${c}/${i}`);
  };

  if (!venueNtable.venue || !venueNtable.table)
      return (
        <VenueNTable
          venues={venues}
          venueNtable={venueNtable}
          setVenueNtable={setVenueNtable}
        />
      );

    return (
    <>
      {!venueNtable.venue || (!venueNtable.table && <VenueNTable venues={venues} venueNtable={venueNtable} setVenueNtable={setVenueNtable} />)}
      <div className="flex flex-col gap-4 grow">
        <div className="searchBar flex flex-col relative gap-4">
          <div className="relative flex  mr-4 items-center max-[350px]:flex-wrap  max-[350px]:justify-center">
            <div className="relative grow mx-4">
              <input type="text" placeholder="Search..." className="w-[98%] mx-auto pl-10 pr-10 py-2 my-2 rounded" value={searchValue} onChange={handleInputChange} />
              <span className="absolute top-[28px] left-2 -translate-y-3">🔍</span>
              <button
                onClick={() => setSearchValue("")}
                className={`absolute top-[28px] right-5 -translate-y-3 ${searchValue ? "" : "hidden"}
									`}>
                ✖
              </button>
            </div>
            <button onClick={() => setToggleFilters(!toggleFilters)} className="whitespace-nowrap bg-[--c1] rounded px-3 border-b-2 border-b-[--c2] text-[--c2] relative inline-block shadow-xl active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none h-[40px] text-4xl">
              <BsFilterRight />
            </button>
            <button
              onClick={() => setToggleGrid(!toggleGrid)}
              className={`md:hidden whitespace-nowrap bg-[--c1] rounded ml-4 px-3 border-b-2 border-b-[--c2] text-[--c2] relative inline-block shadow-xl active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none h-[40px] text-4xl 
								${selectedKCal === "clear" && selectedDietary === "clear" && searchValue === "" ? "" : "hidden"}
								}`}>
              {toggleGrid ? <CiGrid41 /> : <CiGrid2H />}
            </button>
          </div>

          <div className={`${toggleFilters ? "flex" : "hidden"} gap-4 px-4 pb-2 flex-nowrap overflow-auto`}>
            <button name="clear" onClick={handleF1} className={`whitespace-nowrap bg-[--c30] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedKCal === "clear" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              ✖
            </button>
            <button name="300" onClick={handleF1} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedKCal === "300" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              &#60; 300 KCal
            </button>
            <button name="600" onClick={handleF1} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedKCal === "600" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              &#60; 600 KCal
            </button>
            <button name="900" onClick={handleF1} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedKCal === "900" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              &#60; 900 KCal
            </button>
            <button name="1200" onClick={handleF1} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedKCal === "1200" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              &#60; 1200 KCal
            </button>
          </div>
          <div className={`${toggleFilters ? "flex" : "hidden"} gap-4 px-4 pb-2 flex-nowrap overflow-auto`}>
            <button name="clear" onClick={handleF2} className={`whitespace-nowrap bg-[--c30] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedDietary === "clear" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              ✖
            </button>
            <button name="dairy free" onClick={handleF2} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedDietary === "dairy free" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              Dairy Free
            </button>
            <button name="gluten free" onClick={handleF2} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedDietary === "gluten free" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              Gluten Free
            </button>
            <button name="nut free" onClick={handleF2} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedDietary === "nut free" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              Nut Free
            </button>
            <button name="vegan" onClick={handleF2} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedDietary === "vegan" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              Vegan
            </button>
            <button name="vegetarian" onClick={handleF2} className={`whitespace-nowrap bg-[--c1] rounded px-3 py-1 font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block  active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none ${selectedDietary === "vegetarian" ? "shadow-inner shadow-black" : "shadow-xl"}`}>
              Vegetarian
            </button>
          </div>
        </div>

        <div className={`relative  ${toggleGrid ? "grid-cols-1" : "grid-cols-2"} ${selectedKCal === "clear" && selectedDietary === "clear" && searchValue === "" ? "grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2" : "flex"} `}>
          <Outlet />

          {selectedKCal === "clear" && selectedDietary === "clear" && searchValue === "" ? (
            menuitems &&
            menuitems.map((item, index) => (
              <div key={index} className="p-2 flex flex-col cursor-pointer hover:scale-[0.98] transition-all border-b-2 animate-fadeUP1 opacity-0" style={{ animationDelay: `0.${index}s` }} onClick={() => nav(item.name)}>
                <img src={item.img} className="h-[100px] w-[100%]" style={{ objectFit: "cover", overflow: "hidden" }} />
                <div className="flex justify-between items-center">
                  <p>{item.name}</p>
                  <AiFillCaretRight className="bg-[--c1] rounded p-[2px] text-xl font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block shadow-xl active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none" />
                </div>
              </div>
            ))
          ) : (
            <ul className="w-[100%]">
              {menuitems.map((menuItem, index) => {
                // console.log(menuItem);
                return menuItem.items
                  .filter((item) => (item.name.toLowerCase().indexOf(searchValue.toLowerCase()) >= 0 || item.name.toLowerCase().includes(searchValue.toLowerCase()) || item.ingredients.some((ingredient) => ingredient.toLowerCase().includes(searchValue.toLowerCase()))) && (selectedKCal === "clear" || selectedKCal >= item.cal) && (selectedDietary === "clear" || item.allergens.includes(selectedDietary) || item.tag.includes(selectedDietary)))
                  .map((menuItem2, index2) => {
                    // console.log(menuItem2);
                    return (
                      <li key={index2}>
                        <div className="flex border-b-2 p-4 active:bg-[--clsec] hover:scale-[0.98] transition gap-4" onClick={() => handleItemClick(menuItem.name, menuItem2.name)}>
                          <div className="grow">
                            <p className="font-bold text-xl">{menuItem2.name}</p>
                            <p className="text-sm capitalize">
                              {menuItem2.ingredients.map((itemz, index) => (
                                <span key={index}>
                                  <span>{itemz}</span>
                                  {index !== menuItem2.ingredients.length - 1 && <span>, </span>}
                                </span>
                              ))}
                            </p>
                          </div>
                          <div>
                            <p className="font-bold text-xl text-end">£{parseFloat(menuItem2.price).toFixed(2)}</p>
                            <p className="text-sm whitespace-nowrap text-end">{menuItem2.cal} kcal</p>
                          </div>
                          <div>
                            <AiFillCaretRight className=" bg-[--c1] rounded my-auto p-[2px] text-xl font-bold border-b-2 border-b-[--c2] text-[--c2] relative inline-block shadow-xl active:shadow-black active:shadow-inner disabled:bg-[#cecdcd] disabled:text-[#ffffff] disabled:active:shadow-none" />
                          </div>
                        </div>
                      </li>
                    );
                  });
              })}
            </ul>
          )}
        </div>
      </div>
    </>
  );
};

export default Menu;
