import React, { useState, useEffect } from "react";
import "./App.css";
import { auth, db, logout } from "./firebase/config.jsx";

import { Routes, Route, Outlet, NavLink, BrowserRouter } from "react-router-dom";

// Routes
import Layout from "./Layout";

import Menu from "./comp/menu/Menu";
import Auth from "./comp/auth/Auth";
import Signout from "./comp/signout/Signout";
import Basket from "./comp/basket/Basket";
import OrderComplete from "./comp/basket/OrderComplete";
import Page404 from "./comp/Page404";
import Settings from "./comp/Settings/Settings";
import Contact from "./comp/Settings/Contact";
import FAQ from "./comp/Settings/Faq";
import Notifications from "./comp/Settings/Notifications";
import News from "./comp/Settings/News";
import Privacy from "./comp/Settings/Privacy";
import Symbol from "./comp/Settings/Symbol";
import TC from "./comp/Settings/T&C";
import Payment from "./comp/payment/Payment";
import Tables from "./comp/tables/Tables";

import { getVenueById } from "./utils/BasketUtils";

import { loadStripe } from "@stripe/stripe-js";

// mimic db fetch - temporary
let venues = [
  {
    id: 101010,
    name: "The Test Venue",
    email: "testvenue@testvenue.test",
    address: "Test Street, TestCity AA1 1AA",
    phone: "12345 1234 123",
    website: "thetestvenue.test.test",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    coords: [{ long: "52.191724" }, { lat: "-2.220120" }],
  },
  {
    id: 1,
    name: "The White Lion",
    email: "",
    address: "Unit 6, C, Gregory's Mill St, Worcester WR3 8BA",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    coords: [{ long: "52.191724" }, { lat: "-2.220120" }],
  },
  {
    id: 2,
    name: "The Red Lion",
    email: "",
    address: "Unit 1B, Battery Retail Park, Selly Oak, Birmingham B29 6SJ",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 6, 7],
    coords: [{ long: "52.171724" }, { lat: "-2.210120" }],
  },
  {
    id: 3,
    name: "The Black Lion",
    email: "",
    address: "Brompton House, Station Rd, Broadway WR12 7DE",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [15, 16, 17, 18, 19, 20],
    coords: [{ long: "52.161724" }, { lat: "-2.200120" }],
  },
  {
    id: 4,
    name: "The Old Lion Big Name Venue",
    email: "",
    address: "Matson Ln, Matson, Gloucester GL4 6EA",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 18, 19, 20],
    coords: [{ long: "52.151724" }, { lat: "-2.230120" }],
  },
  {
    id: 5,
    name: "The Blue Lion",
    email: "",
    address: "123 Blue Street, Blueville, BL12 3BL",
    phone: "12345 1234 123",
    website: "thebluelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3],
    coords: [{ long: "51.234567" }, { lat: "-1.234567" }],
  },
  {
    id: 6,
    name: "The Green Lion",
    email: "",
    address: "456 Green Road, Greenvale, GR34 5GR",
    phone: "12345 1234 123",
    website: "thegreenlionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [4, 5, 6],
    coords: [{ long: "51.345678" }, { lat: "-1.345678" }],
  },
  {
    id: 7,
    name: "The Yellow Lion",
    email: "",
    address: "789 Yellow Avenue, Yellowtown, YL56 7YL",
    phone: "12345 1234 123",
    website: "theyellowlionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [7, 8, 9],
    coords: [{ long: "51.456789" }, { lat: "-1.456789" }],
  },
  {
    id: 8,
    name: "The Purple Lion",
    email: "",
    address: "987 Purple Close, Purpletown, PT98 7PT",
    phone: "12345 1234 123",
    website: "thepurplelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [10, 11, 12],
    coords: [{ long: "51.567890" }, { lat: "-1.567890" }],
  },
  {
    id: 9,
    name: "The Orange Lion",
    email: "",
    address: "654 Orange Lane, Orangecity, OC65 4OC",
    phone: "12345 1234 123",
    website: "theorangelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [13, 14, 15],
    coords: [{ long: "51.678901" }, { lat: "-1.678901" }],
  },
  {
    id: 10,
    name: "The Pink Lion",
    email: "",
    address: "321 Pink Crescent, Pinkville, PK32 1PK",
    phone: "12345 1234 123",
    website: "thepinklionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [16, 17, 18],
    coords: [{ long: "51.789012" }, { lat: "-1.789012" }],
  },
];
// mimic db fetch - temporary
let dbmenuitems = [
  {
    name: "Breakfast",
    img: "./assets/breakfast.jpg",
    items: [
      {
        name: "Full Breakfast",
        cal: 350,
        tag: [],
        stock: 10,
        ingredients: ["free range eggs", "sausage", "bacon", "mushroom", "tomato", "baked beans", "toast", "butter"],
        price: 10,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Porridge",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["scottish oats", "milk", "honey", "wallnuts", "bannana"],
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: true,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: true,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Avocado on Toast",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["turmeric sourdough", "smashed avocado", "lemon", "cherry tomatoes", "feta cheese", "pomegranades", "watercress", "poached egg", "pine nuts"],
        price: 9,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Scrambled Eggs",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["eggs", "salt", "pepper", "butter"],
        price: 8,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "French Toast",
        cal: 400,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["bread", "eggs", "milk", "cinnamon", "sugar"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 7,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Yogurt Parfait",
        cal: 250,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["yogurt", "granola", "mixed berries", "honey"],
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Protein Pancakes",
        cal: 450,
        tag: [],
        stock: 10,
        ingredients: ["oats", "protein powder", "banana", "eggs", "milk"],
        price: 10,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Veggie Omelette",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["eggs", "bell peppers", "onions", "spinach", "cheese"],
        price: 8,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Kids Starters",
    img: "./assets/kids.jpg",
    items: [
      {
        name: "Kids Mozzarella Sticks",
        tag: ["vegetarian"],
        stock: 10,
        price: 2,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
      },
      {
        name: "Kids Garlic Bread",
        tag: ["vegetarian"],
        stock: 10,
        price: 2,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
      },
      {
        name: "Kids Onion Rings",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 2,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
      },
    ],
  },
  {
    name: "Kids Mains",
    img: "./assets/kids.jpg",
    items: [
      {
        name: "Kids Chicken Nuggets",
        cal: 250,
        tag: [],
        stock: 10,
        ingredients: ["chicken breast", "breadcrumbs", "spices"],
        price: 5,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Cheese Pizza",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["pizza dough", "tomato sauce", "mozzarella cheese"],
        price: 7,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Grilled Cheese Sandwich",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["cheddar", "cheese", "bread", "butter"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 4,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Peanut Butter and Jelly Sandwich",
        cal: 280,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["peanut butter", "jelly", "bread"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 3,
        allergens: [],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Macaroni and Cheese",
        cal: 450,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["macaroni pasta", "cheddar cheese", "milk"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 7,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Mini Pancakes",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["pancake batter", "maple syrup", "fruits"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 6,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Beverages",
    img: "./assets/drinks.jpg",
    items: [
      {
        name: "Coca-Cola",
        tag: ["carbonated", "soft drink"],
        stock: 10,
        price: 2,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "140",
        ingredients: ["Carbonated water", "High fructose corn syrup", "Caramel color", "Phosphoric acid", "Natural flavors", "Caffeine"],
      },
      {
        name: "Orange Juice",
        tag: ["fruit juice", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "110",
        ingredients: ["Orange juice"],
      },
      {
        name: "Apple Juice",
        tag: ["fruit juice", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "120",
        ingredients: ["Apple juice"],
      },
      {
        name: "Lemonade",
        tag: ["carbonated", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "100",
        ingredients: ["Lemon juice", "Water", "Sugar"],
      },
      {
        name: "Iced Tea",
        tag: ["beverage", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "60",
        ingredients: ["Black tea", "Water", "Sugar", "Lemon"],
      },
      {
        name: "Cucumber & Lime Water",
        tag: ["beverage", "non-alcoholic"],
        stock: 10,
        price: 1,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "0",
        ingredients: ["Cucumber", "Lime", "Water"],
      },
      {
        name: "Mango Smoothie",
        tag: ["smoothie", "non-alcoholic"],
        stock: 10,
        price: 4,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "220",
        ingredients: ["Mango", "Yogurt", "Milk", "Honey"],
      },
      {
        name: "Strawberry Banana Smoothie",
        tag: ["smoothie", "non-alcoholic"],
        stock: 10,
        price: 4,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "180",
        ingredients: ["Strawberries", "Banana", "Yogurt", "Milk", "Honey"],
      },
      {
        name: "Chocolate Milkshake",
        tag: ["milkshake", "non-alcoholic"],
        stock: 10,
        price: 5,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "420",
        ingredients: ["Chocolate ice cream", "Milk", "Whipped cream", "Chocolate syrup"],
      },
      {
        name: "Vanilla Milkshake",
        tag: ["milkshake", "non-alcoholic"],
        stock: 10,
        price: 5,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "380",
        ingredients: ["Vanilla ice cream", "Milk", "Whipped cream", "Vanilla extract"],
      },
      {
        name: "Coffee",
        tag: ["hot beverage", "caffeinated"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "5",
        ingredients: ["Coffee beans", "Water"],
      },
      {
        name: "Hot Chocolate",
        tag: ["hot beverage", "non-alcoholic"],
        stock: 10,
        price: 4,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "150",
        ingredients: ["Cocoa powder", "Milk", "Sugar", "Whipped cream", "Chocolate shavings"],
      },
    ],
  },
  {
    name: "Starters",
    img: "./assets/starters.jpg",
    items: [
      {
        name: "Chicken Wings",
        tag: ["chicken", "spicy"],
        stock: 10,
        price: 6,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 400,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Chicken wings", "Hot sauce", "Salt", "Pepper"],
      },
      {
        name: "Mozzarella Sticks",
        tag: ["vegetarian"],
        stock: 10,
        price: 5,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
      },
      {
        name: "Garlic Bread",
        tag: ["vegetarian"],
        stock: 10,
        price: 4,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
      },
      {
        name: "Onion Rings",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 4,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
      },
      {
        name: "Bruschetta",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 5,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Baguette", "Tomatoes", "Garlic", "Basil", "Olive oil"],
      },
      {
        name: "Shrimp Cocktail",
        tag: ["shrimp", "seafood"],
        stock: 10,
        price: 7,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Shrimp", "Cocktail sauce", "Lemon", "Lettuce"],
      },
      {
        name: "Caprese Salad",
        tag: ["vegetarian"],
        stock: 10,
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 200,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Tomatoes", "Mozzarella cheese", "Basil", "Balsamic glaze", "Salt"],
      },
      {
        name: "Spinach Artichoke Dip",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Spinach", "Artichoke hearts", "Cream cheese", "Sour cream", "Parmesan cheese"],
      },
      {
        name: "Crispy Calamari",
        cal: 300,
        tag: [],
        stock: 10,
        ingredients: ["calamari rings", "flour", "spices", "lemon wedges"],
        price: 10,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Mains",
    img: "./assets/mains.jpeg",
    items: [
      {
        name: "Grilled Salmon",
        cal: 400,
        tag: [],
        stock: 10,
        ingredients: ["salmon fillet", "lemon", "dill", "olive oil", "salt", "pepper"],
        price: 15,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Mixed Grill",
        cal: 2100,
        tag: [],
        stock: 10,
        ingredients: ["pork", "lamb", "beef", "sausage", "egg", "black pudding", "chips", "salad", "tomato", "mushroom", "gammon"],
        price: 20,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Beef Burger",
        cal: 500,
        tag: [],
        stock: 10,
        ingredients: ["beef patty", "brioche bun", "lettuce", "tomato", "onion", "cheese", "pickles"],
        price: 12,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Vegetable Stir-Fry",
        cal: 300,
        tag: ["vegetarian", "vegan"],
        stock: 10,
        ingredients: ["mixed vegetables", "tofu", "soy sauce", "ginger", "garlic", "sesame oil"],
        price: 10,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Chicken Parmesan",
        cal: 450,
        tag: [],
        stock: 10,
        ingredients: ["chicken breast", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
        price: 14,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Pesto Pasta",
        cal: 380,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["penne pasta", "basil pesto", "cherry tomatoes", "pine nuts", "Parmesan cheese"],
        price: 11,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Shrimp Scampi",
        cal: 320,
        tag: [],
        stock: 10,
        ingredients: ["shrimp", "breadcrumbs", "lemon", "tartare", "chips", "salad", "parsley"],
        price: 16,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Mushroom Risotto",
        cal: 380,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["arborio rice", "mushrooms", "onion", "garlic", "vegetable broth", "Parmesan cheese"],
        price: 13,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Grilled Chicken Caesar Salad",
        cal: 320,
        tag: [],
        stock: 10,
        ingredients: ["grilled chicken breast", "romaine lettuce", "croutons", "Parmesan cheese", "Caesar dressing"],
        price: 9,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Beef Stroganoff",
        cal: 480,
        tag: [],
        stock: 10,
        ingredients: ["beef sirloin", "mushrooms", "onion", "garlic", "sour cream", "beef broth", "egg noodles"],
        price: 15,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Fish and Chips",
        cal: 550,
        tag: [],
        stock: 10,
        ingredients: ["white fish fillets", "flour", "beer", "potatoes", "tartar sauce", "lemon wedges"],
        price: 13,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Eggplant Parmesan",
        cal: 420,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["eggplant", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
        price: 12,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Lemon Herb Roasted Chicken",
        cal: 400,
        tag: [],
        stock: 10,
        ingredients: ["chicken", "lemon", "rosemary", "thyme", "garlic", "butter", "potatoes", "carrots"],
        price: 16,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Vegetable Lasagna",
        cal: 360,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["lasagna noodles", "spinach", "mushrooms", "zucchini", "ricotta cheese", "marinara sauce", "mozzarella cheese"],
        price: 14,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Desserts",
    img: "./assets/deserts.jpg",
    items: [
      {
        name: "Chocolate Brownie",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["chocolate", "butter", "sugar", "eggs", "flour", "vanilla extract", "walnuts"],
        price: 8,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Cheesecake",
        cal: 450,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["graham cracker crumbs", "butter", "cream cheese", "sugar", "sour cream", "vanilla extract", "eggs", "strawberry topping"],
        price: 8,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Vanilla Ice Cream",
        cal: 200,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["cream", "sugar", "vanilla extract"],
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Fruit Tart",
        cal: 250,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["pastry dough", "pastry cream", "strawberries", "kiwi", "blueberries", "apricot glaze"],
        price: 10,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Tiramisu",
        cal: 320,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["ladyfingers", "espresso", "mascarpone cheese", "sugar", "cocoa powder", "rum or coffee liqueur"],
        price: 9,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Strawberry Shortcake",
        cal: 280,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["shortcakes", "strawberries", "whipped cream", "sugar", "vanilla extract"],
        price: 6,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
];

// mimic db fetch - temporary
let dbtables = [
  {
    id: "6e3eb8e5-60e0-44d9-96b9-bf3d34085123",
    area: "Bar",
    tn: 16,
    x: 728,
    y: 385.29,
    type: "table",
    seats: 2,
    height: 100,
    width: 100,
  },
  {
    id: "6e3eb8e5-60e0-44d9-96b9-bf3d34085124",
    area: "Bar",
    tn: 10,
    x: 117.35,
    y: 83.3,
    type: "table",
    seats: 1,
    height: 110,
    width: 100,
  },
  {
    id: "6e3eb8e5-60e0-44d9-96b9-bf3d34085125",
    area: "Bar",
    tn: 18,
    x: 914.68,
    y: 85.34,
    type: "table",
    seats: 8,
    height: 120,
    width: 180,
  },
  {
    id: "6e3eb8e5-60e0-44d9-96b9-bf3d34085550",
    area: "Bar",
    tn: 0,
    x: 22.64,
    y: 9.35,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "6b878ceb-6227-419d-984d-fc03d159d9ae",
    area: "Restaurant",
    tn: 0,
    x: 20.02,
    y: 381.34,
    type: "wall",
    seats: 0,
    height: 160,
    width: 10,
  },
  {
    id: "fdebfef5-c747-4f5d-ace0-fcf19d2ff424",
    area: "Restaurant",
    tn: 6,
    x: 170.69,
    y: 18.72,
    type: "table",
    seats: 4,
    height: 190,
    width: 70,
  },
  {
    id: "7adb45c8-6c8b-40d6-b178-12097eb04307",
    area: "Restaurant",
    tn: 0,
    x: 17.33,
    y: 13.29,
    type: "wall",
    seats: 0,
    height: 200,
    width: 10,
  },
  {
    id: "f3696e9e-075c-4c72-a3d6-0dd476ba1a2c",
    area: "Restaurant",
    tn: 0,
    x: 1162.59,
    y: 4.02,
    type: "wall",
    seats: 0,
    height: 260,
    width: 30,
  },
  {
    id: "ef997146-6047-40a5-8b04-a1ea697968a0",
    area: "Restaurant",
    tn: 0,
    x: 1162.57,
    y: 279.92,
    type: "wall",
    seats: 0,
    height: 240,
    width: 30,
  },
  {
    id: "d28bf95a-2c46-41cd-aac9-9f9e17ede031",
    area: "Restaurant",
    tn: 5,
    x: 154.63,
    y: 389.97,
    type: "table",
    seats: 2,
    height: 110,
    width: 110,
  },
  {
    id: "689f7410-c548-4d95-a97a-6587191e3e35",
    area: "Restaurant",
    tn: 8,
    x: 613.38,
    y: 3.98,
    type: "table",
    seats: 4,
    height: 230,
    width: 80,
  },
  {
    id: "787e204b-2f4e-451d-9ae3-0848d4aff15b",
    area: "Restaurant",
    tn: 4,
    x: 361.31,
    y: 394.69,
    type: "table",
    seats: 2,
    height: 110,
    width: 120,
  },
  {
    id: "86f62c1a-7cd9-4f6b-90b0-70ab5f2266d1",
    area: "Restaurant",
    tn: 7,
    x: 381.32,
    y: 10.71,
    type: "table",
    seats: 4,
    height: 200,
    width: 70,
  },
  {
    id: "3750e9f2-ea8e-492f-bc1e-8eefbaeca998",
    area: "Restaurant",
    tn: 3,
    x: 578.65,
    y: 391.99,
    type: "table",
    seats: 1,
    height: 110,
    width: 110,
  },
  {
    id: "98ab080e-b8b8-486f-aa7b-3a5a8751a87f",
    area: "Restaurant",
    tn: 1,
    x: 982.64,
    y: 399.99,
    type: "table",
    seats: 2,
    height: 110,
    width: 110,
  },
  {
    id: "0368e6fe-c9cd-49ad-b01e-423ea470f0ff",
    area: "Restaurant",
    tn: 2,
    x: 774.7,
    y: 393.34,
    type: "table",
    seats: 2,
    height: 110,
    width: 110,
  },
  {
    id: "7f449e17-6ce9-442b-8deb-3dcd5b424cd8",
    area: "Restaurant",
    tn: 9,
    x: 824.02,
    y: 34.63,
    type: "table",
    seats: 12,
    height: 180,
    width: 250,
  },
  {
    id: "3cc6ae8c-cba0-4b6f-8e06-73e90b07ca07",
    area: "Bar",
    tn: 12,
    x: 544.62,
    y: 88.6,
    type: "table",
    seats: 3,
    height: 100,
    width: 110,
  },
  {
    id: "892ef9ef-7a3a-4e91-84e9-6dacada44604",
    area: "Bar",
    tn: 11,
    x: 323.95,
    y: 87.93,
    type: "table",
    seats: 2,
    height: 100,
    width: 100,
  },
  {
    id: "c3703c84-6e62-401e-bf59-2cdd00fe2589",
    area: "Bar",
    tn: 0,
    x: 372.66,
    y: 11.36,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "f4a92d69-3a0c-494e-b0a6-23588695f790",
    area: "Bar",
    tn: 0,
    x: -1.3,
    y: 542.71,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "1dacc4b6-8588-4719-b943-e210080c554d",
    area: "Bar",
    tn: 0,
    x: 319.36,
    y: 541.99,
    type: "wall",
    seats: 0,
    height: 10,
    width: 290,
  },
  {
    id: "6443412d-bf10-4418-9f89-a1efb977648a",
    area: "Bar",
    tn: 0,
    x: 630.7,
    y: 541.33,
    type: "wall",
    seats: 0,
    height: 10,
    width: 250,
  },
  {
    id: "de38e1bd-4f94-4f6f-b811-d7e648e59494",
    area: "Bar",
    tn: 0,
    x: 896,
    y: 543.33,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "3c5836f6-51f7-4391-acfd-c3eec26c6c97",
    area: "Bar",
    tn: 0,
    x: 891.99,
    y: 10.7,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "c855c612-75b8-4ec2-bf0c-f9862791946c",
    area: "Bar",
    tn: 0,
    x: 6.7,
    y: 50.72,
    type: "wall",
    seats: 0,
    height: 140,
    width: 10,
  },
  {
    id: "31ebc9c8-180d-40b3-b1e2-c3c9a70b4777",
    area: "Bar",
    tn: 0,
    x: 0.71,
    y: 384.71,
    type: "wall",
    seats: 0,
    height: 140,
    width: 10,
  },
  {
    id: "c9347386-36e2-4968-8904-e12474070848",
    area: "Bar",
    tn: 0,
    x: 1186,
    y: 35.41,
    type: "wall",
    seats: 0,
    height: 200,
    width: 10,
  },
  {
    id: "a567ba82-a5c9-40fc-844d-3e8af2b81d84",
    area: "Bar",
    tn: 0,
    x: 1183.37,
    y: 250.04,
    type: "wall",
    seats: 0,
    height: 270,
    width: 10,
  },
  {
    id: "a57afe3d-5623-42df-9034-7b61ab719ede",
    area: "Bar",
    tn: 17,
    x: 928.63,
    y: 361.99,
    type: "table",
    seats: 8,
    height: 120,
    width: 180,
  },
  {
    id: "69b064a3-9d9c-4b72-80ea-dc765376cd2a",
    area: "Bar",
    tn: 13,
    x: 131.39,
    y: 380.66,
    type: "table",
    seats: 2,
    height: 100,
    width: 100,
  },
  {
    id: "2beac11a-7193-4159-be19-fdedf2dab52b",
    area: "Bar",
    tn: 14,
    x: 318.71,
    y: 378.69,
    type: "table",
    seats: 2,
    height: 100,
    width: 100,
  },
  {
    id: "1144ad9f-3123-4d47-a6c8-d3ddc50851b8",
    area: "Bar",
    tn: 15,
    x: 522.01,
    y: 386.01,
    type: "table",
    seats: 2,
    height: 100,
    width: 100,
  },
  {
    id: "1134367b-033d-498b-81b2-5f9faa8d514f",
    area: "Pantry",
    tn: 21,
    x: 754.54,
    y: 169.37,
    type: "table",
    seats: 16,
    height: 270,
    width: 300,
  },
  {
    id: "21ac8195-24f9-4bfe-9c65-41bbd47f0ff5",
    area: "Pantry",
    tn: 20,
    x: 149.91,
    y: 180.66,
    type: "table",
    seats: 16,
    height: 270,
    width: 300,
  },
  {
    id: "d2ba582d-0cd1-49ad-9457-463e2b162cf7",
    area: "Pantry",
    tn: 0,
    x: 1182.67,
    y: 1.34,
    type: "wall",
    seats: 0,
    height: 300,
    width: 10,
  },
  {
    id: "4a7e6bdf-87af-4332-a4e6-5a487cb222be",
    area: "Pantry",
    tn: 0,
    x: 1184.71,
    y: 326,
    type: "wall",
    seats: 0,
    height: 230,
    width: 10,
  },
  {
    id: "649df853-995a-4b2f-a55d-76b459c39e20",
    area: "Pantry",
    tn: 0,
    x: 8.05,
    y: 326,
    type: "wall",
    seats: 0,
    height: 230,
    width: 10,
  },
  {
    id: "d15c59da-ac84-483e-b2bb-f231ee656e35",
    area: "Pantry",
    tn: 0,
    x: 6.73,
    y: 3.96,
    type: "wall",
    seats: 0,
    height: 300,
    width: 10,
  },
  {
    id: "c9c3a912-7541-415e-9634-43c2b4977a6c",
    area: "Pantry",
    tn: 0,
    x: 867.35,
    y: 544.67,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "218d36a1-78db-447c-b000-12655a5298bb",
    area: "Pantry",
    tn: 0,
    x: 85.36,
    y: 596,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "0a9e2b3c-a845-4530-946b-e5cd22e0de3f",
    area: "Pantry",
    tn: 0,
    x: 36.04,
    y: 546,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "9c6555ff-b1b4-4f71-8226-0c3a649dbe24",
    area: "Pantry",
    tn: 0,
    x: 355.41,
    y: 546,
    type: "wall",
    seats: 0,
    height: 10,
    width: 230,
  },
  {
    id: "f7dc9c99-2e2a-4998-bf66-68aa447dd10b",
    area: "Pantry",
    tn: 0,
    x: 613.42,
    y: 546,
    type: "wall",
    seats: 0,
    height: 10,
    width: 240,
  },
  {
    id: "a2578496-b4cc-400b-b9f3-26c8472edc03",
    area: "Pantry",
    tn: 0,
    x: 574.07,
    y: 221.94,
    type: "wall",
    seats: 0,
    height: 300,
    width: 10,
  },
  {
    id: "5c929b86-2366-4d94-a162-11a2b6b9d33e",
    area: "Pantry",
    tn: 0,
    x: 42.13,
    y: 1.32,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
  {
    id: "92bf1866-fc07-4366-a221-f16c07013b5b",
    area: "Pantry",
    tn: 0,
    x: 856.1,
    y: 3.33,
    type: "wall",
    seats: 0,
    height: 10,
    width: 300,
  },
];

const App = () => {
  const [user, setUser] = useState(null);
  const [basketItems, setBasketItems] = useState([]);
  const [venueNtable, setVenueNtable] = useState({ venue: 1, table: null });

  const [tables, setTables] = useState([]);
  const [draggingIndex, setDraggingIndex] = useState(null);
  const [showArea, setshowArea] = useState("Bar");
  const [uniqueAreas, setuniqueAreas] = useState([]);

  useEffect(() => {
    if (!tables || tables.length < 1) return;
    setuniqueAreas([...new Set(tables.map((table) => table.area))]);
  }, [tables]);

  useEffect(() => {
    let x = basketItems
      .reduce((total, item) => {
        return total + item.price * item.qty;
      }, 0)
      .toFixed(2);

    const handleKeyPress = (event) => {
      if (event.key === "F9") {
        console.log(basketItems, x, tables);
      }
    };
    window.addEventListener("keydown", handleKeyPress);
    return () => {
      window.removeEventListener("keydown", handleKeyPress);
    };
  }, [basketItems, tables]);

  const [menuitems, setMenuitems] = useState([]);
  const [searchValue, setSearchValue] = useState("");
  const [basketQty, setBasketQty] = useState(0);

  const calculateTotalQuantity = () => {
    const totalQty = basketItems.reduce((total, item) => total + parseInt(item.qty), 0);
    setBasketQty(totalQty);
  };

  useEffect(() => {
    async function getMenu() {
      // fetch simulation of setting the menu from the database - temporary
      setMenuitems(dbmenuitems);
    }
    getMenu();

    async function getTables() {
      setTables(dbtables);
    }
    getTables();
  }, []);

  useEffect(() => {
    calculateTotalQuantity();
  }, [basketItems]);

  return (
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route path="/" element={<Auth />} />

        <Route path="/tables" element={<Tables tables={tables} setTables={setTables} draggingIndex={draggingIndex} setDraggingIndex={setDraggingIndex} showArea={showArea} setshowArea={setshowArea} uniqueAreas={uniqueAreas} setuniqueAreas={setuniqueAreas} venues={venues} venueNtable={venueNtable} setVenueNtable={setVenueNtable} />} />

        <Route path="/menu" element={<Menu basketItems={basketItems} setBasketItems={setBasketItems} menuitems={menuitems} searchValue={searchValue} setSearchValue={setSearchValue} venueNtable={venueNtable} setVenueNtable={setVenueNtable} venues={venues} />}></Route>

        <Route path="/payment" element={<Payment setVenueNtable={setVenueNtable} venueNtable={venueNtable} basketItems={basketItems} setBasketItems={setBasketItems} user={user} />} />

        <Route path="/settings" element={<Settings venues={venues} />} />

        <Route path="/contact" element={<Contact />} />
        <Route path="/faq" element={<FAQ />} />
        <Route path="/notifications" element={<Notifications />} />
        <Route path="/news" element={<News />} />
        <Route path="/privacy" element={<Privacy />} />
        <Route path="/symbol" element={<Symbol />} />
        <Route path="/t&c" element={<TC />} />

        <Route path="/signout" element={<Signout setUser={setUser} setVenueNtable={setVenueNtable} />} />

        <Route path="*" element={<Page404 />} />
      </Route>
    </Routes>
  );
};

export default App;
