import React, { useState, useEffect } from "react";
import "./App.css";
import { auth, db, logout } from "./firebase/config.jsx";

import { Routes, Route, Outlet, NavLink, BrowserRouter } from "react-router-dom";

// Routes
import Layout from "./Layout";

import Menu from "./comp/menu/Menu";
import Auth from "./comp/auth/Auth";
import Signout from "./comp/signout/Signout";
import Basket from "./comp/basket/Basket";
import OrderComplete from "./comp/basket/OrderComplete";
import Page404 from "./comp/Page404";
import Settings from "./comp/Settings/Settings";
import Contact from "./comp/Settings/Contact";
import FAQ from "./comp/Settings/Faq";
import Notifications from "./comp/Settings/Notifications";
import News from "./comp/Settings/News";
import Privacy from "./comp/Settings/Privacy";
import Symbol from "./comp/Settings/Symbol";
import TC from "./comp/Settings/T&C";
import Payment from "./comp/payment/Payment";
import Tables from "./comp/tables/Tables";

import { getVenueById } from "./utils/BasketUtils";

import { loadStripe } from "@stripe/stripe-js";

// mimic db fetch - temporary
const venues = [
  {
    id: 101010,
    name: "The Test Venue",
    email: "testvenue@testvenue.test",
    address: "Test Street, TestCity AA1 1AA",
    phone: "12345 1234 123",
    website: "thetestvenue.test.test",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    coords: [{ long: "52.191724" }, { lat: "-2.220120" }],
  },
  {
    id: 1,
    name: "The White Lion",
    email: "",
    address: "Unit 6, C, Gregory's Mill St, Worcester WR3 8BA",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    coords: [{ long: "52.191724" }, { lat: "-2.220120" }],
  },
  {
    id: 2,
    name: "The Red Lion",
    email: "",
    address: "Unit 1B, Battery Retail Park, Selly Oak, Birmingham B29 6SJ",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 6, 7],
    coords: [{ long: "52.171724" }, { lat: "-2.210120" }],
  },
  {
    id: 3,
    name: "The Black Lion",
    email: "",
    address: "Brompton House, Station Rd, Broadway WR12 7DE",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [15, 16, 17, 18, 19, 20],
    coords: [{ long: "52.161724" }, { lat: "-2.200120" }],
  },
  {
    id: 4,
    name: "The Old Lion Big Name Venue",
    email: "",
    address: "Matson Ln, Matson, Gloucester GL4 6EA",
    phone: "12345 1234 123",
    website: "theawesomelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3, 4, 5, 18, 19, 20],
    coords: [{ long: "52.151724" }, { lat: "-2.230120" }],
  },
  {
    id: 5,
    name: "The Blue Lion",
    email: "",
    address: "123 Blue Street, Blueville, BL12 3BL",
    phone: "12345 1234 123",
    website: "thebluelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [1, 2, 3],
    coords: [{ long: "51.234567" }, { lat: "-1.234567" }],
  },
  {
    id: 6,
    name: "The Green Lion",
    email: "",
    address: "456 Green Road, Greenvale, GR34 5GR",
    phone: "12345 1234 123",
    website: "thegreenlionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [4, 5, 6],
    coords: [{ long: "51.345678" }, { lat: "-1.345678" }],
  },
  {
    id: 7,
    name: "The Yellow Lion",
    email: "",
    address: "789 Yellow Avenue, Yellowtown, YL56 7YL",
    phone: "12345 1234 123",
    website: "theyellowlionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [7, 8, 9],
    coords: [{ long: "51.456789" }, { lat: "-1.456789" }],
  },
  {
    id: 8,
    name: "The Purple Lion",
    email: "",
    address: "987 Purple Close, Purpletown, PT98 7PT",
    phone: "12345 1234 123",
    website: "thepurplelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [10, 11, 12],
    coords: [{ long: "51.567890" }, { lat: "-1.567890" }],
  },
  {
    id: 9,
    name: "The Orange Lion",
    email: "",
    address: "654 Orange Lane, Orangecity, OC65 4OC",
    phone: "12345 1234 123",
    website: "theorangelionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [13, 14, 15],
    coords: [{ long: "51.678901" }, { lat: "-1.678901" }],
  },
  {
    id: 10,
    name: "The Pink Lion",
    email: "",
    address: "321 Pink Crescent, Pinkville, PK32 1PK",
    phone: "12345 1234 123",
    website: "thepinklionwebsite.co.uk",
    img: "./assets/defaultVenue.jpg",
    table: [16, 17, 18],
    coords: [{ long: "51.789012" }, { lat: "-1.789012" }],
  },
];
// mimic db fetch - temporary
const dbmenuitems = [
  {
    name: "Breakfast",
    img: "./assets/breakfast.jpg",
    items: [
      {
        name: "Full Breakfast",
        cal: 350,
        tag: [],
        stock: 10,
        ingredients: ["free range eggs", "sausage", "bacon", "mushroom", "tomato", "baked beans", "toast", "butter"],
        price: 10,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Porridge",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["scottish oats", "milk", "honey", "wallnuts", "bannana"],
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: true,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: true,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Avocado on Toast",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["turmeric sourdough", "smashed avocado", "lemon", "cherry tomatoes", "feta cheese", "pomegranades", "watercress", "poached egg", "pine nuts"],
        price: 9,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Scrambled Eggs",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["eggs", "salt", "pepper", "butter"],
        price: 8,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "French Toast",
        cal: 400,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["bread", "eggs", "milk", "cinnamon", "sugar"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 7,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Yogurt Parfait",
        cal: 250,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["yogurt", "granola", "mixed berries", "honey"],
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Protein Pancakes",
        cal: 450,
        tag: [],
        stock: 10,
        ingredients: ["oats", "protein powder", "banana", "eggs", "milk"],
        price: 10,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Veggie Omelette",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["eggs", "bell peppers", "onions", "spinach", "cheese"],
        price: 8,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Kids Starters",
    img: "./assets/kids.jpg",
    items: [
      {
        name: "Kids Mozzarella Sticks",
        tag: ["vegetarian"],
        stock: 10,
        price: 2,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
      },
      {
        name: "Kids Garlic Bread",
        tag: ["vegetarian"],
        stock: 10,
        price: 2,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
      },
      {
        name: "Kids Onion Rings",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 2,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
      },
    ],
  },
  {
    name: "Kids Mains",
    img: "./assets/kids.jpg",
    items: [
      {
        name: "Kids Chicken Nuggets",
        cal: 250,
        tag: [],
        stock: 10,
        ingredients: ["chicken breast", "breadcrumbs", "spices"],
        price: 5,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Cheese Pizza",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["pizza dough", "tomato sauce", "mozzarella cheese"],
        price: 7,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Grilled Cheese Sandwich",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["cheddar", "cheese", "bread", "butter"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 4,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Peanut Butter and Jelly Sandwich",
        cal: 280,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["peanut butter", "jelly", "bread"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 3,
        allergens: [],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Macaroni and Cheese",
        cal: 450,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["macaroni pasta", "cheddar cheese", "milk"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 7,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Kids Mini Pancakes",
        cal: 300,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["pancake batter", "maple syrup", "fruits"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        price: 6,
        allergens: ["nut free"],
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Beverages",
    img: "./assets/drinks.jpg",
    items: [
      {
        name: "Coca-Cola",
        tag: ["carbonated", "soft drink"],
        stock: 10,
        price: 2,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "140",
        ingredients: ["Carbonated water", "High fructose corn syrup", "Caramel color", "Phosphoric acid", "Natural flavors", "Caffeine"],
      },
      {
        name: "Orange Juice",
        tag: ["fruit juice", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "110",
        ingredients: ["Orange juice"],
      },
      {
        name: "Apple Juice",
        tag: ["fruit juice", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "120",
        ingredients: ["Apple juice"],
      },
      {
        name: "Lemonade",
        tag: ["carbonated", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "100",
        ingredients: ["Lemon juice", "Water", "Sugar"],
      },
      {
        name: "Iced Tea",
        tag: ["beverage", "non-alcoholic"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "60",
        ingredients: ["Black tea", "Water", "Sugar", "Lemon"],
      },
      {
        name: "Cucumber & Lime Water",
        tag: ["beverage", "non-alcoholic"],
        stock: 10,
        price: 1,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "0",
        ingredients: ["Cucumber", "Lime", "Water"],
      },
      {
        name: "Mango Smoothie",
        tag: ["smoothie", "non-alcoholic"],
        stock: 10,
        price: 4,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "220",
        ingredients: ["Mango", "Yogurt", "Milk", "Honey"],
      },
      {
        name: "Strawberry Banana Smoothie",
        tag: ["smoothie", "non-alcoholic"],
        stock: 10,
        price: 4,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "180",
        ingredients: ["Strawberries", "Banana", "Yogurt", "Milk", "Honey"],
      },
      {
        name: "Chocolate Milkshake",
        tag: ["milkshake", "non-alcoholic"],
        stock: 10,
        price: 5,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "420",
        ingredients: ["Chocolate ice cream", "Milk", "Whipped cream", "Chocolate syrup"],
      },
      {
        name: "Vanilla Milkshake",
        tag: ["milkshake", "non-alcoholic"],
        stock: 10,
        price: 5,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "380",
        ingredients: ["Vanilla ice cream", "Milk", "Whipped cream", "Vanilla extract"],
      },
      {
        name: "Coffee",
        tag: ["hot beverage", "caffeinated"],
        stock: 10,
        price: 3,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "5",
        ingredients: ["Coffee beans", "Water"],
      },
      {
        name: "Hot Chocolate",
        tag: ["hot beverage", "non-alcoholic"],
        stock: 10,
        price: 4,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDrink.jpg",
        calories: "150",
        ingredients: ["Cocoa powder", "Milk", "Sugar", "Whipped cream", "Chocolate shavings"],
      },
    ],
  },
  {
    name: "Starters",
    img: "./assets/starters.jpg",
    items: [
      {
        name: "Chicken Wings",
        tag: ["chicken", "spicy"],
        stock: 10,
        price: 6,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 400,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Chicken wings", "Hot sauce", "Salt", "Pepper"],
      },
      {
        name: "Mozzarella Sticks",
        tag: ["vegetarian"],
        stock: 10,
        price: 5,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Mozzarella cheese sticks", "Breadcrumbs", "Eggs", "Flour", "Marinara sauce"],
      },
      {
        name: "Garlic Bread",
        tag: ["vegetarian"],
        stock: 10,
        price: 4,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Baguette", "Garlic", "Butter", "Parsley", "Salt"],
      },
      {
        name: "Onion Rings",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 4,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Onions", "Flour", "Baking powder", "Salt", "Milk"],
      },
      {
        name: "Bruschetta",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 5,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Baguette", "Tomatoes", "Garlic", "Basil", "Olive oil"],
      },
      {
        name: "Shrimp Cocktail",
        tag: ["shrimp", "seafood"],
        stock: 10,
        price: 7,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Shrimp", "Cocktail sauce", "Lemon", "Lettuce"],
      },
      {
        name: "Caprese Salad",
        tag: ["vegetarian"],
        stock: 10,
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 200,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Tomatoes", "Mozzarella cheese", "Basil", "Balsamic glaze", "Salt"],
      },
      {
        name: "Spinach Artichoke Dip",
        tag: ["vegetarian", "vegan"],
        stock: 10,
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        cal: 300,
        img: "./assets/defaultDish.jpg",
        ingredients: ["Spinach", "Artichoke hearts", "Cream cheese", "Sour cream", "Parmesan cheese"],
      },
      {
        name: "Crispy Calamari",
        cal: 300,
        tag: [],
        stock: 10,
        ingredients: ["calamari rings", "flour", "spices", "lemon wedges"],
        price: 10,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Mains",
    img: "./assets/mains.jpeg",
    items: [
      {
        name: "Grilled Salmon",
        cal: 400,
        tag: [],
        stock: 10,
        ingredients: ["salmon fillet", "lemon", "dill", "olive oil", "salt", "pepper"],
        price: 15,
        allergens: ["nut free", "gluten free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Mixed Grill",
        cal: 2100,
        tag: [],
        stock: 10,
        ingredients: ["pork", "lamb", "beef", "sausage", "egg", "black pudding", "chips", "salad", "tomato", "mushroom", "gammon"],
        price: 20,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Beef Burger",
        cal: 500,
        tag: [],
        stock: 10,
        ingredients: ["beef patty", "brioche bun", "lettuce", "tomato", "onion", "cheese", "pickles"],
        price: 12,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Vegetable Stir-Fry",
        cal: 300,
        tag: ["vegetarian", "vegan"],
        stock: 10,
        ingredients: ["mixed vegetables", "tofu", "soy sauce", "ginger", "garlic", "sesame oil"],
        price: 10,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Chicken Parmesan",
        cal: 450,
        tag: [],
        stock: 10,
        ingredients: ["chicken breast", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
        price: 14,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Pesto Pasta",
        cal: 380,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["penne pasta", "basil pesto", "cherry tomatoes", "pine nuts", "Parmesan cheese"],
        price: 11,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Shrimp Scampi",
        cal: 320,
        tag: [],
        stock: 10,
        ingredients: ["shrimp", "breadcrumbs", "lemon", "tartare", "chips", "salad", "parsley"],
        price: 16,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Mushroom Risotto",
        cal: 380,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["arborio rice", "mushrooms", "onion", "garlic", "vegetable broth", "Parmesan cheese"],
        price: 13,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Grilled Chicken Caesar Salad",
        cal: 320,
        tag: [],
        stock: 10,
        ingredients: ["grilled chicken breast", "romaine lettuce", "croutons", "Parmesan cheese", "Caesar dressing"],
        price: 9,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Beef Stroganoff",
        cal: 480,
        tag: [],
        stock: 10,
        ingredients: ["beef sirloin", "mushrooms", "onion", "garlic", "sour cream", "beef broth", "egg noodles"],
        price: 15,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Fish and Chips",
        cal: 550,
        tag: [],
        stock: 10,
        ingredients: ["white fish fillets", "flour", "beer", "potatoes", "tartar sauce", "lemon wedges"],
        price: 13,
        allergens: ["nut free", "dairy free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Eggplant Parmesan",
        cal: 420,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["eggplant", "bread crumbs", "Parmesan cheese", "marinara sauce", "mozzarella cheese", "spaghetti"],
        price: 12,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Lemon Herb Roasted Chicken",
        cal: 400,
        tag: [],
        stock: 10,
        ingredients: ["chicken", "lemon", "rosemary", "thyme", "garlic", "butter", "potatoes", "carrots"],
        price: 16,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Vegetable Lasagna",
        cal: 360,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["lasagna noodles", "spinach", "mushrooms", "zucchini", "ricotta cheese", "marinara sauce", "mozzarella cheese"],
        price: 14,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
  {
    name: "Desserts",
    img: "./assets/deserts.jpg",
    items: [
      {
        name: "Chocolate Brownie",
        cal: 350,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["chocolate", "butter", "sugar", "eggs", "flour", "vanilla extract", "walnuts"],
        price: 8,
        allergens: [],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Cheesecake",
        cal: 450,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["graham cracker crumbs", "butter", "cream cheese", "sugar", "sour cream", "vanilla extract", "eggs", "strawberry topping"],
        price: 8,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Vanilla Ice Cream",
        cal: 200,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["cream", "sugar", "vanilla extract"],
        price: 6,
        allergens: ["nut free", "gluten free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Fruit Tart",
        cal: 250,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["pastry dough", "pastry cream", "strawberries", "kiwi", "blueberries", "apricot glaze"],
        price: 10,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Tiramisu",
        cal: 320,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["ladyfingers", "espresso", "mascarpone cheese", "sugar", "cocoa powder", "rum or coffee liqueur"],
        price: 9,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
      {
        name: "Strawberry Shortcake",
        cal: 280,
        tag: ["vegetarian"],
        stock: 10,
        ingredients: ["shortcakes", "strawberries", "whipped cream", "sugar", "vanilla extract"],
        price: 6,
        allergens: ["nut free"],
        priceOffer: null,
        allergensList: {
          Meat: false,
          Celery: false,
          Crustaceans: false,
          Fish: false,
          Milk: false,
          Mustard: false,
          Peanuts: false,
          Soybeans: false,
          Gluten: false,
          Egg: false,
          Lupin: false,
          Moluscs: false,
          Nuts: false,
          SesameSeeds: false,
          Sulphur: false,
        },
        img: "./assets/defaultDish.jpg",
      },
    ],
  },
];
// await grabProducts()

const App = () => {
  const [user, setUser] = useState(null);
  const [basketItems, setBasketItems] = useState([]);
  const [venueNtable, setVenueNtable] = useState({ venue: 1, table: null });

  const [menuitems, setMenuitems] = useState([]);
  const [toggleGrid, setToggleGrid] = useState(false);
  const [toggleFilters, setToggleFilters] = useState(false);
  const [searchValue, setSearchValue] = useState("");
  const [basketQty, setBasketQty] = useState(0);

  const calculateTotalQuantity = () => {
    const totalQty = basketItems.reduce((total, item) => total + parseInt(item.qty), 0);
    setBasketQty(totalQty);
  };

  useEffect(() => {
    async function get() {
      // fetch simulation of setting the menu from the database - temporary
      setMenuitems(dbmenuitems);
    }
    get();
  }, []);

  useEffect(() => {
    calculateTotalQuantity();
  }, [basketItems]);

  return (
    <Routes>
      <Route path="/" element={<Layout basketQty={basketQty} />}>

        <Route path="/" element={<Auth />} />

        <Route path="/tables" element={<Tables />} />

        <Route path="/menu" element={<Menu basketItems={basketItems} setBasketItems={setBasketItems} menuitems={menuitems} searchValue={searchValue} setSearchValue={setSearchValue} venueNtable={venueNtable} setVenueNtable={setVenueNtable} venues={venues} />}>
          
        </Route>
        
        <Route path="/payment" element={<Payment setVenueNtable={setVenueNtable} venueNtable={venueNtable} basketItems={basketItems} setBasketItems={setBasketItems} user={user}/>} />

        <Route path="/settings" element={<Settings venues={venues} />} />

        <Route path="/contact" element={<Contact />} />
        <Route path="/faq" element={<FAQ />} />
        <Route path="/notifications" element={<Notifications />} />
        <Route path="/news" element={<News />} />
        <Route path="/privacy" element={<Privacy />} />
        <Route path="/symbol" element={<Symbol />} />
        <Route path="/t&c" element={<TC />} />

        <Route path="/signout" element={<Signout setUser={setUser} setVenueNtable={setVenueNtable} />} />

        <Route path="*" element={<Page404 />} />
      </Route>
    </Routes>
  );
};

export default App;
